//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createNewOrder complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="createNewOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="input" type="{http://ws.lite.neworder/}newOrderInputInfo" minOccurs="0"/>
 *         &lt;element name="output" type="{http://ws.lite.neworder/}newOrderOutputInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createNewOrder", propOrder = {
    "input",
    "output"
})
public class CreateNewOrder
    implements Serializable
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 2993971345943602857L;
	protected NewOrderInputInfo input;
    protected NewOrderOutputInfo output;

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link NewOrderInputInfo }
     *     
     */
    public NewOrderInputInfo getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewOrderInputInfo }
     *     
     */
    public void setInput(NewOrderInputInfo value) {
        this.input = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link NewOrderOutputInfo }
     *     
     */
    public NewOrderOutputInfo getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewOrderOutputInfo }
     *     
     */
    public void setOutput(NewOrderOutputInfo value) {
        this.output = value;
    }

}
