//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import jakarta.xml.ws.WebFault;

@WebFault(name = "Exception", targetNamespace = "http://ws.lite.neworder/")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -3478936011401955895L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private neworder.lite.ws.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, neworder.lite.ws.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, neworder.lite.ws.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: neworder.lite.ws.Exception
     */
    public neworder.lite.ws.Exception getFaultInfo() {
        return faultInfo;
    }

}
