//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for newOrderSingleItemOutInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="newOrderSingleItemOutInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outBrandGeneric" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outItemId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="outItemName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outItemPrice" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="outItemQuantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="outItemSupplyWarehouseId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="outItemTotal" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="outStockQuantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newOrderSingleItemOutInfo", propOrder = {
    "outBrandGeneric",
    "outItemId",
    "outItemName",
    "outItemPrice",
    "outItemQuantity",
    "outItemSupplyWarehouseId",
    "outItemTotal",
    "outStockQuantity"
})
public class NewOrderSingleItemOutInfo
    implements Serializable
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 6146846236183887928L;
	protected String outBrandGeneric;
    protected int outItemId;
    protected String outItemName;
    protected double outItemPrice;
    protected int outItemQuantity;
    protected short outItemSupplyWarehouseId;
    protected double outItemTotal;
    protected int outStockQuantity;

    /**
     * Gets the value of the outBrandGeneric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutBrandGeneric() {
        return outBrandGeneric;
    }

    /**
     * Sets the value of the outBrandGeneric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutBrandGeneric(String value) {
        this.outBrandGeneric = value;
    }

    /**
     * Gets the value of the outItemId property.
     * 
     */
    public int getOutItemId() {
        return outItemId;
    }

    /**
     * Sets the value of the outItemId property.
     * 
     */
    public void setOutItemId(int value) {
        this.outItemId = value;
    }

    /**
     * Gets the value of the outItemName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutItemName() {
        return outItemName;
    }

    /**
     * Sets the value of the outItemName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutItemName(String value) {
        this.outItemName = value;
    }

    /**
     * Gets the value of the outItemPrice property.
     * 
     */
    public double getOutItemPrice() {
        return outItemPrice;
    }

    /**
     * Sets the value of the outItemPrice property.
     * 
     */
    public void setOutItemPrice(double value) {
        this.outItemPrice = value;
    }

    /**
     * Gets the value of the outItemQuantity property.
     * 
     */
    public int getOutItemQuantity() {
        return outItemQuantity;
    }

    /**
     * Sets the value of the outItemQuantity property.
     * 
     */
    public void setOutItemQuantity(int value) {
        this.outItemQuantity = value;
    }

    /**
     * Gets the value of the outItemSupplyWarehouseId property.
     * 
     */
    public short getOutItemSupplyWarehouseId() {
        return outItemSupplyWarehouseId;
    }

    /**
     * Sets the value of the outItemSupplyWarehouseId property.
     * 
     */
    public void setOutItemSupplyWarehouseId(short value) {
        this.outItemSupplyWarehouseId = value;
    }

    /**
     * Gets the value of the outItemTotal property.
     * 
     */
    public double getOutItemTotal() {
        return outItemTotal;
    }

    /**
     * Sets the value of the outItemTotal property.
     * 
     */
    public void setOutItemTotal(double value) {
        this.outItemTotal = value;
    }

    /**
     * Gets the value of the outStockQuantity property.
     * 
     */
    public int getOutStockQuantity() {
        return outStockQuantity;
    }

    /**
     * Sets the value of the outStockQuantity property.
     * 
     */
    public void setOutStockQuantity(int value) {
        this.outStockQuantity = value;
    }

}
