//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;

@WebServiceClient(name = "NewOrderImplService", targetNamespace = "http://ws.lite.neworder/", wsdlLocation = "WEB-INF/wsdl/NewOrderImplService.wsdl")
public class NewOrderImplService
    extends Service
{

    private final static URL NEWORDERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException NEWORDERIMPLSERVICE_EXCEPTION;
    private final static QName NEWORDERIMPLSERVICE_QNAME = new QName("http://ws.lite.neworder/", "NewOrderImplService");

    static {
            NEWORDERIMPLSERVICE_WSDL_LOCATION = neworder.lite.ws.NewOrderImplService.class.getResource("/WEB-INF/wsdl/NewOrderImplService.wsdl");
        WebServiceException e = null;
        if (NEWORDERIMPLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/NewOrderImplService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        NEWORDERIMPLSERVICE_EXCEPTION = e;
    }

    public NewOrderImplService() {
        super(__getWsdlLocation(), NEWORDERIMPLSERVICE_QNAME);
    }

    public NewOrderImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEWORDERIMPLSERVICE_QNAME, features);
    }

    public NewOrderImplService(URL wsdlLocation) {
        super(wsdlLocation, NEWORDERIMPLSERVICE_QNAME);
    }

    public NewOrderImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEWORDERIMPLSERVICE_QNAME, features);
    }

    public NewOrderImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NewOrderImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NewOrderImplDelegate
     */
    @WebEndpoint(name = "NewOrderImplPort")
    public NewOrderImplDelegate getNewOrderImplPort() {
        return super.getPort(new QName("http://ws.lite.neworder/", "NewOrderImplPort"), NewOrderImplDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NewOrderImplDelegate
     */
    @WebEndpoint(name = "NewOrderImplPort")
    public NewOrderImplDelegate getNewOrderImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lite.neworder/", "NewOrderImplPort"), NewOrderImplDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEWORDERIMPLSERVICE_EXCEPTION!= null) {
            throw NEWORDERIMPLSERVICE_EXCEPTION;
        }
        return NEWORDERIMPLSERVICE_WSDL_LOCATION;
    }

}
