//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for newOrderSingleItemInInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="newOrderSingleItemInInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inItemId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="inItemQuantity" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="inItemSupplyWarehouseId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newOrderSingleItemInInfo", propOrder = {
    "inItemId",
    "inItemQuantity",
    "inItemSupplyWarehouseId"
})
public class NewOrderSingleItemInInfo
    implements Serializable
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -7366704353035343870L;
	protected int inItemId;
    protected int inItemQuantity;
    protected short inItemSupplyWarehouseId;

    /**
     * Gets the value of the inItemId property.
     * 
     */
    public int getInItemId() {
        return inItemId;
    }

    /**
     * Sets the value of the inItemId property.
     * 
     */
    public void setInItemId(int value) {
        this.inItemId = value;
    }

    /**
     * Gets the value of the inItemQuantity property.
     * 
     */
    public int getInItemQuantity() {
        return inItemQuantity;
    }

    /**
     * Sets the value of the inItemQuantity property.
     * 
     */
    public void setInItemQuantity(int value) {
        this.inItemQuantity = value;
    }

    /**
     * Gets the value of the inItemSupplyWarehouseId property.
     * 
     */
    public short getInItemSupplyWarehouseId() {
        return inItemSupplyWarehouseId;
    }

    /**
     * Sets the value of the inItemSupplyWarehouseId property.
     * 
     */
    public void setInItemSupplyWarehouseId(short value) {
        this.inItemSupplyWarehouseId = value;
    }

}
