//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for newOrderInputInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="newOrderInputInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="distributedEJBs" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="entityType" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="inCustomerId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="inDistrictId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="inItemList" type="{http://ws.lite.neworder/}newOrderSingleItemInInfo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="inOrderEntryDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="inWareHouseId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="numberOfItems" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="originatorIsJavaClient" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newOrderInputInfo", propOrder = {
    "distributedEJBs",
    "entityType",
    "inCustomerId",
    "inDistrictId",
    "inItemList",
    "inOrderEntryDate",
    "inWareHouseId",
    "numberOfItems",
    "originatorIsJavaClient"
})
public class NewOrderInputInfo
    implements Serializable
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 378798783066864066L;
	protected boolean distributedEJBs;
    protected short entityType;
    protected short inCustomerId;
    protected short inDistrictId;
    @XmlElement(nillable = true)
    protected List<NewOrderSingleItemInInfo> inItemList;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar inOrderEntryDate;
    protected short inWareHouseId;
    protected int numberOfItems;
    protected boolean originatorIsJavaClient;

    /**
     * Gets the value of the distributedEJBs property.
     * 
     */
    public boolean isDistributedEJBs() {
        return distributedEJBs;
    }

    /**
     * Sets the value of the distributedEJBs property.
     * 
     */
    public void setDistributedEJBs(boolean value) {
        this.distributedEJBs = value;
    }

    /**
     * Gets the value of the entityType property.
     * 
     */
    public short getEntityType() {
        return entityType;
    }

    /**
     * Sets the value of the entityType property.
     * 
     */
    public void setEntityType(short value) {
        this.entityType = value;
    }

    /**
     * Gets the value of the inCustomerId property.
     * 
     */
    public short getInCustomerId() {
        return inCustomerId;
    }

    /**
     * Sets the value of the inCustomerId property.
     * 
     */
    public void setInCustomerId(short value) {
        this.inCustomerId = value;
    }

    /**
     * Gets the value of the inDistrictId property.
     * 
     */
    public short getInDistrictId() {
        return inDistrictId;
    }

    /**
     * Sets the value of the inDistrictId property.
     * 
     */
    public void setInDistrictId(short value) {
        this.inDistrictId = value;
    }

    /**
     * Gets the value of the inItemList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inItemList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInItemList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NewOrderSingleItemInInfo }
     * 
     * 
     */
    public List<NewOrderSingleItemInInfo> getInItemList() {
        if (inItemList == null) {
            inItemList = new ArrayList<NewOrderSingleItemInInfo>();
        }
        return this.inItemList;
    }

    /**
     * Gets the value of the inOrderEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInOrderEntryDate() {
        return inOrderEntryDate;
    }

    /**
     * Sets the value of the inOrderEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInOrderEntryDate(XMLGregorianCalendar value) {
        this.inOrderEntryDate = value;
    }

    /**
     * Gets the value of the inWareHouseId property.
     * 
     */
    public short getInWareHouseId() {
        return inWareHouseId;
    }

    /**
     * Sets the value of the inWareHouseId property.
     * 
     */
    public void setInWareHouseId(short value) {
        this.inWareHouseId = value;
    }

    /**
     * Gets the value of the numberOfItems property.
     * 
     */
    public int getNumberOfItems() {
        return numberOfItems;
    }

    /**
     * Sets the value of the numberOfItems property.
     * 
     */
    public void setNumberOfItems(int value) {
        this.numberOfItems = value;
    }

    /**
     * Gets the value of the originatorIsJavaClient property.
     * 
     */
    public boolean isOriginatorIsJavaClient() {
        return originatorIsJavaClient;
    }

    /**
     * Sets the value of the originatorIsJavaClient property.
     * 
     */
    public void setOriginatorIsJavaClient(boolean value) {
        this.originatorIsJavaClient = value;
    }

}
