//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the neworder.lite.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateNewOrder_QNAME = new QName("http://ws.lite.neworder/", "createNewOrder");
    private final static QName _CreateNewOrderResponse_QNAME = new QName("http://ws.lite.neworder/", "createNewOrderResponse");
    private final static QName _Exception_QNAME = new QName("http://ws.lite.neworder/", "Exception");
    private final static QName _SystemException_QNAME = new QName("http://ws.lite.neworder/", "SystemException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: neworder.lite.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemException }
     * 
     */
    public SystemException createSystemException() {
        return new SystemException();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link CreateNewOrderResponse }
     * 
     */
    public CreateNewOrderResponse createCreateNewOrderResponse() {
        return new CreateNewOrderResponse();
    }

    /**
     * Create an instance of {@link CreateNewOrder }
     * 
     */
    public CreateNewOrder createCreateNewOrder() {
        return new CreateNewOrder();
    }

    /**
     * Create an instance of {@link NewOrderOutputInfo }
     * 
     */
    public NewOrderOutputInfo createNewOrderOutputInfo() {
        return new NewOrderOutputInfo();
    }

    /**
     * Create an instance of {@link NewOrderSingleItemOutInfo }
     * 
     */
    public NewOrderSingleItemOutInfo createNewOrderSingleItemOutInfo() {
        return new NewOrderSingleItemOutInfo();
    }

    /**
     * Create an instance of {@link NewOrderInputInfo }
     * 
     */
    public NewOrderInputInfo createNewOrderInputInfo() {
        return new NewOrderInputInfo();
    }

    /**
     * Create an instance of {@link NewOrderSingleItemInInfo }
     * 
     */
    public NewOrderSingleItemInInfo createNewOrderSingleItemInInfo() {
        return new NewOrderSingleItemInInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateNewOrder }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.neworder/", name = "createNewOrder")
    public JAXBElement<CreateNewOrder> createCreateNewOrder(CreateNewOrder value) {
        return new JAXBElement<CreateNewOrder>(_CreateNewOrder_QNAME, CreateNewOrder.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateNewOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.neworder/", name = "createNewOrderResponse")
    public JAXBElement<CreateNewOrderResponse> createCreateNewOrderResponse(CreateNewOrderResponse value) {
        return new JAXBElement<CreateNewOrderResponse>(_CreateNewOrderResponse_QNAME, CreateNewOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.neworder/", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.neworder/", name = "SystemException")
    public JAXBElement<SystemException> createSystemException(SystemException value) {
        return new JAXBElement<SystemException>(_SystemException_QNAME, SystemException.class, null, value);
    }

}
