//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package neworder.lite.ws;

import jakarta.xml.ws.WebFault;

@WebFault(name = "SystemException", targetNamespace = "http://ws.lite.neworder/")
public class SystemException_Exception
    extends java.lang.Exception
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 3943477420836331181L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private SystemException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SystemException_Exception(String message, SystemException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SystemException_Exception(String message, SystemException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: neworder.lite.ws.SystemException
     */
    public SystemException getFaultInfo() {
        return faultInfo;
    }

}
