kind: Deployment
apiVersion: apps/v1
metadata:
  name: erww-db2
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: erww-db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erww-db2
      deployment: erww-db2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: erww-db2
        deployment: erww-db2
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: erww-db2
          env:
            - name: DB2INST1_PASSWORD
              value: letme1n2.2021Q1
            - name: LICENSE
              value: accept
            - name: APP
              value: erww
          securityContext:
            capabilities:
            privileged: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
          ports:
            - containerPort: 50000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: docker-na-public.artifactory.swg-devops.com/hyc-wassvt-team-image-registry-docker-local/db2/svt-db2:latest
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: mysvcacct
      serviceAccount: mysvcacct
      schedulerName: default-scheduler
