package irwwbase;

/**
 * Insert the type's description here.
 * Creation date: (12/09/00 15:45:20)
 * @author: Administrator
 */
import java.sql.*;
 
//import java.rmi.*;
//import jakarta.ejb.*;

public class ExtendedDatabase extends irwwbase.IRWWBase {
	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 2517306648338595544L;
	protected static java.lang.String _className;

	public ExtendedDatabase() {
		super();
		_className = (ExtendedDatabase.class).getName();
	}
	
	protected Connection getConnection() throws java.rmi.RemoteException, UserException {
		// MD11455 changed signature to include SessionCtx so CMT can set Rollback for DataIntegrity 
		Connection currentConnection = null;
		
		// load a driver and create a connection
		try
		{
			Class.forName("COM.ibm.db2.jdbc.app.DB2Driver");
			currentConnection = DriverManager.getConnection("jdbc:db2:IRWWDB");
		} catch (Exception ex) {
	        System.out.println("ERROR: " + _className + ".getConnection() failed where currentConnection = " + currentConnection);
	        ex.printStackTrace();
	    }
		
		return currentConnection;
	}
}