package orderarchive.lite;

/**
 * Class for OrderArchiveSerlet.java's manual user input
 */
public class OrderArchiveInput implements  java.io.Serializable
{
	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -5054053397790942621L;
	private short warehouseId;
	private short districtId;
	private int numOrders;

	// Constructor
	public OrderArchiveInput() {
		super();
	}

	

	// Getters 
	public short getWarehouseId() {
		return warehouseId;
	}


	public short getDistrictId() {
		return districtId;
	}

	public int getNumOrders() {
		return numOrders;
	}

	
	
	// Setters
	public void setWarehouseId(short newWarehouseId) {
		warehouseId = newWarehouseId;
	}

	public void setDistrictId(short newDistrictId) {
		districtId = newDistrictId;
	}

	public void setNumOrders(short newNumOrders) {
		numOrders = newNumOrders;
	}



}