//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import jakarta.xml.ws.WebFault;

@WebFault(name = "String", targetNamespace = "http://ws.lite.orderstatus/")
public class ERWWDataNotFoundException
    extends java.lang.Exception
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 537354840682304831L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private String faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ERWWDataNotFoundException(String message, String faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public ERWWDataNotFoundException(String message, String faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: java.lang.String
     */
    public String getFaultInfo() {
        return faultInfo;
    }

}
