//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import jakarta.xml.ws.WebFault;

@WebFault(name = "IOException", targetNamespace = "http://ws.lite.orderstatus/")
public class IOException_Exception
    extends java.lang.Exception
{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 7443101859665802968L;
	/**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IOException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IOException_Exception(String message, IOException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public IOException_Exception(String message, IOException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: orderstatus.lite.ws.IOException
     */
    public IOException getFaultInfo() {
        return faultInfo;
    }

}
