//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the orderstatus.lite.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IOException_QNAME = new QName("http://ws.lite.orderstatus/", "IOException");
    private final static QName _SQLException_QNAME = new QName("http://ws.lite.orderstatus/", "SQLException");
    private final static QName _GetOrderStatus_QNAME = new QName("http://ws.lite.orderstatus/", "getOrderStatus");
    private final static QName _PrintOrderStatusOutput_QNAME = new QName("http://ws.lite.orderstatus/", "printOrderStatusOutput");
    private final static QName _GetOrderStatusResponse_QNAME = new QName("http://ws.lite.orderstatus/", "getOrderStatusResponse");
    private final static QName _PrintOrderStatusOutputResponse_QNAME = new QName("http://ws.lite.orderstatus/", "printOrderStatusOutputResponse");
    private final static QName _Exception_QNAME = new QName("http://ws.lite.orderstatus/", "Exception");
    private final static QName _String_QNAME = new QName("http://ws.lite.orderstatus/", "String");
    private final static QName _ExceptionMessage_QNAME = new QName("", "message");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: orderstatus.lite.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SQLException }
     * 
     */
    public SQLException createSQLException() {
        return new SQLException();
    }

    /**
     * Create an instance of {@link PrintOrderStatusOutput }
     * 
     */
    public PrintOrderStatusOutput createPrintOrderStatusOutput() {
        return new PrintOrderStatusOutput();
    }

    /**
     * Create an instance of {@link PrintOrderStatusOutputResponse }
     * 
     */
    public PrintOrderStatusOutputResponse createPrintOrderStatusOutputResponse() {
        return new PrintOrderStatusOutputResponse();
    }

    /**
     * Create an instance of {@link IOException }
     * 
     */
    public IOException createIOException() {
        return new IOException();
    }

    /**
     * Create an instance of {@link GetOrderStatus }
     * 
     */
    public GetOrderStatus createGetOrderStatus() {
        return new GetOrderStatus();
    }

    /**
     * Create an instance of {@link GetOrderStatusResponse }
     * 
     */
    public GetOrderStatusResponse createGetOrderStatusResponse() {
        return new GetOrderStatusResponse();
    }

    /**
     * Create an instance of {@link Exception }
     * 
     */
    public Exception createException() {
        return new Exception();
    }

    /**
     * Create an instance of {@link OrderStatusOutput }
     * 
     */
    public OrderStatusOutput createOrderStatusOutput() {
        return new OrderStatusOutput();
    }

    /**
     * Create an instance of {@link OrderStatusInput }
     * 
     */
    public OrderStatusInput createOrderStatusInput() {
        return new OrderStatusInput();
    }

    /**
     * Create an instance of {@link OrderLineSingleItem }
     * 
     */
    public OrderLineSingleItem createOrderLineSingleItem() {
        return new OrderLineSingleItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IOException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "IOException")
    public JAXBElement<IOException> createIOException(IOException value) {
        return new JAXBElement<IOException>(_IOException_QNAME, IOException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SQLException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "SQLException")
    public JAXBElement<SQLException> createSQLException(SQLException value) {
        return new JAXBElement<SQLException>(_SQLException_QNAME, SQLException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "getOrderStatus")
    public JAXBElement<GetOrderStatus> createGetOrderStatus(GetOrderStatus value) {
        return new JAXBElement<GetOrderStatus>(_GetOrderStatus_QNAME, GetOrderStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintOrderStatusOutput }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "printOrderStatusOutput")
    public JAXBElement<PrintOrderStatusOutput> createPrintOrderStatusOutput(PrintOrderStatusOutput value) {
        return new JAXBElement<PrintOrderStatusOutput>(_PrintOrderStatusOutput_QNAME, PrintOrderStatusOutput.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "getOrderStatusResponse")
    public JAXBElement<GetOrderStatusResponse> createGetOrderStatusResponse(GetOrderStatusResponse value) {
        return new JAXBElement<GetOrderStatusResponse>(_GetOrderStatusResponse_QNAME, GetOrderStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PrintOrderStatusOutputResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "printOrderStatusOutputResponse")
    public JAXBElement<PrintOrderStatusOutputResponse> createPrintOrderStatusOutputResponse(PrintOrderStatusOutputResponse value) {
        return new JAXBElement<PrintOrderStatusOutputResponse>(_PrintOrderStatusOutputResponse_QNAME, PrintOrderStatusOutputResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "Exception")
    public JAXBElement<Exception> createException(Exception value) {
        return new JAXBElement<Exception>(_Exception_QNAME, Exception.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.lite.orderstatus/", name = "String")
    public JAXBElement<String> createString(String value) {
        return new JAXBElement<String>(_String_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "message", scope = Exception.class)
    public JAXBElement<String> createExceptionMessage(String value) {
        return new JAXBElement<String>(_ExceptionMessage_QNAME, String.class, Exception.class, value);
    }

}
