//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

@WebService(name = "OrderStatusImpl", targetNamespace = "http://ws.lite.orderstatus/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderStatusImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns orderstatus.lite.ws.OrderStatusOutput
     * @throws ERWWDataNotFoundException
     * @throws IOException_Exception
     * @throws SQLException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderStatus", targetNamespace = "http://ws.lite.orderstatus/", className = "orderstatus.lite.ws.GetOrderStatus")
    @ResponseWrapper(localName = "getOrderStatusResponse", targetNamespace = "http://ws.lite.orderstatus/", className = "orderstatus.lite.ws.GetOrderStatusResponse")
    public OrderStatusOutput getOrderStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderStatusInput arg0)
        throws ERWWDataNotFoundException, Exception_Exception, IOException_Exception, SQLException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws IOException_Exception
     * @throws SQLException_Exception
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "printOrderStatusOutput", targetNamespace = "http://ws.lite.orderstatus/", className = "orderstatus.lite.ws.PrintOrderStatusOutput")
    @ResponseWrapper(localName = "printOrderStatusOutputResponse", targetNamespace = "http://ws.lite.orderstatus/", className = "orderstatus.lite.ws.PrintOrderStatusOutputResponse")
    public void printOrderStatusOutput(
        @WebParam(name = "arg0", targetNamespace = "")
        OrderStatusOutput arg0)
        throws Exception_Exception, IOException_Exception, SQLException_Exception
    ;

}
