//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;

@WebServiceClient(name = "OrderStatusImplService", targetNamespace = "http://ws.lite.orderstatus/", wsdlLocation = "WEB-INF/wsdl/OrderStatusImplService.wsdl")
public class OrderStatusImplService
    extends Service
{

    private final static URL ORDERSTATUSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERSTATUSIMPLSERVICE_EXCEPTION;
    private final static QName ORDERSTATUSIMPLSERVICE_QNAME = new QName("http://ws.lite.orderstatus/", "OrderStatusImplService");

    static {
            ORDERSTATUSIMPLSERVICE_WSDL_LOCATION = orderstatus.lite.ws.OrderStatusImplService.class.getResource("/WEB-INF/wsdl/OrderStatusImplService.wsdl");
        WebServiceException e = null;
        if (ORDERSTATUSIMPLSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'WEB-INF/wsdl/OrderStatusImplService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        ORDERSTATUSIMPLSERVICE_EXCEPTION = e;
    }

    public OrderStatusImplService() {
        super(__getWsdlLocation(), ORDERSTATUSIMPLSERVICE_QNAME);
    }

    public OrderStatusImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERSTATUSIMPLSERVICE_QNAME, features);
    }

    public OrderStatusImplService(URL wsdlLocation) {
        super(wsdlLocation, ORDERSTATUSIMPLSERVICE_QNAME);
    }

    public OrderStatusImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERSTATUSIMPLSERVICE_QNAME, features);
    }

    public OrderStatusImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderStatusImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderStatusImpl
     */
    @WebEndpoint(name = "OrderStatusImplPort")
    public OrderStatusImpl getOrderStatusImplPort() {
        return super.getPort(new QName("http://ws.lite.orderstatus/", "OrderStatusImplPort"), OrderStatusImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderStatusImpl
     */
    @WebEndpoint(name = "OrderStatusImplPort")
    public OrderStatusImpl getOrderStatusImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lite.orderstatus/", "OrderStatusImplPort"), OrderStatusImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERSTATUSIMPLSERVICE_EXCEPTION!= null) {
            throw ORDERSTATUSIMPLSERVICE_EXCEPTION;
        }
        return ORDERSTATUSIMPLSERVICE_WSDL_LOCATION;
    }

}
