//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderLineSingleItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderLineSingleItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outOlAmount" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="outOlDeliveryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outOlItemId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="outOlQuantity" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="outOlSupplyWarehouseId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderLineSingleItem", propOrder = {
    "outOlAmount",
    "outOlDeliveryDate",
    "outOlItemId",
    "outOlQuantity",
    "outOlSupplyWarehouseId"
})
public class OrderLineSingleItem {

    protected double outOlAmount;
    protected String outOlDeliveryDate;
    protected int outOlItemId;
    protected double outOlQuantity;
    protected short outOlSupplyWarehouseId;

    /**
     * Gets the value of the outOlAmount property.
     * 
     */
    public double getOutOlAmount() {
        return outOlAmount;
    }

    /**
     * Sets the value of the outOlAmount property.
     * 
     */
    public void setOutOlAmount(double value) {
        this.outOlAmount = value;
    }

    /**
     * Gets the value of the outOlDeliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutOlDeliveryDate() {
        return outOlDeliveryDate;
    }

    /**
     * Sets the value of the outOlDeliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutOlDeliveryDate(String value) {
        this.outOlDeliveryDate = value;
    }

    /**
     * Gets the value of the outOlItemId property.
     * 
     */
    public int getOutOlItemId() {
        return outOlItemId;
    }

    /**
     * Sets the value of the outOlItemId property.
     * 
     */
    public void setOutOlItemId(int value) {
        this.outOlItemId = value;
    }

    /**
     * Gets the value of the outOlQuantity property.
     * 
     */
    public double getOutOlQuantity() {
        return outOlQuantity;
    }

    /**
     * Sets the value of the outOlQuantity property.
     * 
     */
    public void setOutOlQuantity(double value) {
        this.outOlQuantity = value;
    }

    /**
     * Gets the value of the outOlSupplyWarehouseId property.
     * 
     */
    public short getOutOlSupplyWarehouseId() {
        return outOlSupplyWarehouseId;
    }

    /**
     * Sets the value of the outOlSupplyWarehouseId property.
     * 
     */
    public void setOutOlSupplyWarehouseId(short value) {
        this.outOlSupplyWarehouseId = value;
    }

}
