//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderStatusInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderStatusInput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="distributedEJBs" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inByLastName" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="inCustomerDistrictId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="inCustomerId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="inCustomerLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inCustomerWarehouseId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="useCmp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderStatusInput", propOrder = {
    "distributedEJBs",
    "inByLastName",
    "inCustomerDistrictId",
    "inCustomerId",
    "inCustomerLastName",
    "inCustomerWarehouseId",
    "useCmp"
})
public class OrderStatusInput {

    protected boolean distributedEJBs;
    protected boolean inByLastName;
    protected short inCustomerDistrictId;
    protected short inCustomerId;
    protected String inCustomerLastName;
    protected short inCustomerWarehouseId;
    protected boolean useCmp;

    /**
     * Gets the value of the distributedEJBs property.
     * 
     */
    public boolean isDistributedEJBs() {
        return distributedEJBs;
    }

    /**
     * Sets the value of the distributedEJBs property.
     * 
     */
    public void setDistributedEJBs(boolean value) {
        this.distributedEJBs = value;
    }

    /**
     * Gets the value of the inByLastName property.
     * 
     */
    public boolean isInByLastName() {
        return inByLastName;
    }

    /**
     * Sets the value of the inByLastName property.
     * 
     */
    public void setInByLastName(boolean value) {
        this.inByLastName = value;
    }

    /**
     * Gets the value of the inCustomerDistrictId property.
     * 
     */
    public short getInCustomerDistrictId() {
        return inCustomerDistrictId;
    }

    /**
     * Sets the value of the inCustomerDistrictId property.
     * 
     */
    public void setInCustomerDistrictId(short value) {
        this.inCustomerDistrictId = value;
    }

    /**
     * Gets the value of the inCustomerId property.
     * 
     */
    public short getInCustomerId() {
        return inCustomerId;
    }

    /**
     * Sets the value of the inCustomerId property.
     * 
     */
    public void setInCustomerId(short value) {
        this.inCustomerId = value;
    }

    /**
     * Gets the value of the inCustomerLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInCustomerLastName() {
        return inCustomerLastName;
    }

    /**
     * Sets the value of the inCustomerLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInCustomerLastName(String value) {
        this.inCustomerLastName = value;
    }

    /**
     * Gets the value of the inCustomerWarehouseId property.
     * 
     */
    public short getInCustomerWarehouseId() {
        return inCustomerWarehouseId;
    }

    /**
     * Sets the value of the inCustomerWarehouseId property.
     * 
     */
    public void setInCustomerWarehouseId(short value) {
        this.inCustomerWarehouseId = value;
    }

    /**
     * Gets the value of the useCmp property.
     * 
     */
    public boolean isUseCmp() {
        return useCmp;
    }

    /**
     * Sets the value of the useCmp property.
     * 
     */
    public void setUseCmp(boolean value) {
        this.useCmp = value;
    }

}
