//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//


package orderstatus.lite.ws;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for orderStatusOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="orderStatusOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outCustomerBalance" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="outCustomerDistrictId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="outCustomerFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outCustomerId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="outCustomerLastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outCustomerMiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outCustomerWarehouseId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="outErrorMsg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outOrderCarrierId" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="outOrderEntryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="outOrderId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="outOrderLineCount" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *         &lt;element name="outOrderLines" type="{http://ws.lite.orderstatus/}orderLineSingleItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="retc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stcnum" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "orderStatusOutput", propOrder = {
    "outCustomerBalance",
    "outCustomerDistrictId",
    "outCustomerFirstName",
    "outCustomerId",
    "outCustomerLastName",
    "outCustomerMiddleName",
    "outCustomerWarehouseId",
    "outErrorMsg",
    "outOrderCarrierId",
    "outOrderEntryDate",
    "outOrderId",
    "outOrderLineCount",
    "outOrderLines",
    "retc",
    "stcnum"
})
public class OrderStatusOutput {

    protected double outCustomerBalance;
    protected short outCustomerDistrictId;
    protected String outCustomerFirstName;
    protected short outCustomerId;
    protected String outCustomerLastName;
    protected String outCustomerMiddleName;
    protected short outCustomerWarehouseId;
    protected String outErrorMsg;
    protected short outOrderCarrierId;
    protected String outOrderEntryDate;
    protected int outOrderId;
    protected short outOrderLineCount;
    @XmlElement(nillable = true)
    protected List<OrderLineSingleItem> outOrderLines;
    protected String retc;
    protected String stcnum;

    /**
     * Gets the value of the outCustomerBalance property.
     * 
     */
    public double getOutCustomerBalance() {
        return outCustomerBalance;
    }

    /**
     * Sets the value of the outCustomerBalance property.
     * 
     */
    public void setOutCustomerBalance(double value) {
        this.outCustomerBalance = value;
    }

    /**
     * Gets the value of the outCustomerDistrictId property.
     * 
     */
    public short getOutCustomerDistrictId() {
        return outCustomerDistrictId;
    }

    /**
     * Sets the value of the outCustomerDistrictId property.
     * 
     */
    public void setOutCustomerDistrictId(short value) {
        this.outCustomerDistrictId = value;
    }

    /**
     * Gets the value of the outCustomerFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutCustomerFirstName() {
        return outCustomerFirstName;
    }

    /**
     * Sets the value of the outCustomerFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutCustomerFirstName(String value) {
        this.outCustomerFirstName = value;
    }

    /**
     * Gets the value of the outCustomerId property.
     * 
     */
    public short getOutCustomerId() {
        return outCustomerId;
    }

    /**
     * Sets the value of the outCustomerId property.
     * 
     */
    public void setOutCustomerId(short value) {
        this.outCustomerId = value;
    }

    /**
     * Gets the value of the outCustomerLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutCustomerLastName() {
        return outCustomerLastName;
    }

    /**
     * Sets the value of the outCustomerLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutCustomerLastName(String value) {
        this.outCustomerLastName = value;
    }

    /**
     * Gets the value of the outCustomerMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutCustomerMiddleName() {
        return outCustomerMiddleName;
    }

    /**
     * Sets the value of the outCustomerMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutCustomerMiddleName(String value) {
        this.outCustomerMiddleName = value;
    }

    /**
     * Gets the value of the outCustomerWarehouseId property.
     * 
     */
    public short getOutCustomerWarehouseId() {
        return outCustomerWarehouseId;
    }

    /**
     * Sets the value of the outCustomerWarehouseId property.
     * 
     */
    public void setOutCustomerWarehouseId(short value) {
        this.outCustomerWarehouseId = value;
    }

    /**
     * Gets the value of the outErrorMsg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutErrorMsg() {
        return outErrorMsg;
    }

    /**
     * Sets the value of the outErrorMsg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutErrorMsg(String value) {
        this.outErrorMsg = value;
    }

    /**
     * Gets the value of the outOrderCarrierId property.
     * 
     */
    public short getOutOrderCarrierId() {
        return outOrderCarrierId;
    }

    /**
     * Sets the value of the outOrderCarrierId property.
     * 
     */
    public void setOutOrderCarrierId(short value) {
        this.outOrderCarrierId = value;
    }

    /**
     * Gets the value of the outOrderEntryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutOrderEntryDate() {
        return outOrderEntryDate;
    }

    /**
     * Sets the value of the outOrderEntryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutOrderEntryDate(String value) {
        this.outOrderEntryDate = value;
    }

    /**
     * Gets the value of the outOrderId property.
     * 
     */
    public int getOutOrderId() {
        return outOrderId;
    }

    /**
     * Sets the value of the outOrderId property.
     * 
     */
    public void setOutOrderId(int value) {
        this.outOrderId = value;
    }

    /**
     * Gets the value of the outOrderLineCount property.
     * 
     */
    public short getOutOrderLineCount() {
        return outOrderLineCount;
    }

    /**
     * Sets the value of the outOrderLineCount property.
     * 
     */
    public void setOutOrderLineCount(short value) {
        this.outOrderLineCount = value;
    }

    /**
     * Gets the value of the outOrderLines property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outOrderLines property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutOrderLines().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderLineSingleItem }
     * 
     * 
     */
    public List<OrderLineSingleItem> getOutOrderLines() {
        if (outOrderLines == null) {
            outOrderLines = new ArrayList<OrderLineSingleItem>();
        }
        return this.outOrderLines;
    }

    /**
     * Gets the value of the retc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetc() {
        return retc;
    }

    /**
     * Sets the value of the retc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetc(String value) {
        this.retc = value;
    }

    /**
     * Gets the value of the stcnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStcnum() {
        return stcnum;
    }

    /**
     * Sets the value of the stcnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStcnum(String value) {
        this.stcnum = value;
    }

}
