//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:17 AM(foreman)-)
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ws.lite.orderstatus/")
package orderstatus.lite.ws;
