apiVersion: v1
kind: Service
metadata:
  name: erwwlite
  labels:
    name: erwwlite
spec:
  selector:
    name: erwwlite
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9080
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 9443
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: erwwlite
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: erwwlite
    spec:
      containers:
      - name: erwwlite
        image: erww-lite-jee7:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
          - containerPort: 9443
        readinessProbe:
          httpGet:
            path: /
            port: 9080
        env:
        - name: MB_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-keystore-password
              key: password
        - name: MB_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mb-truststore-password
              key: password
        volumeMounts:
          - name: keystores
            mountPath: /etc/wlp/config/keystore
            readOnly: true
          - name: truststores
            mountPath: /etc/wlp/config/truststore
            readOnly: true
          - name: liberty-config
            mountPath: /config/configDropins
      volumes:
        - name: keystores
          secret:
            secretName: mb-keystore
        - name: truststores
          secret:
            secretName: mb-truststore
        - name: liberty-config
          configMap:
            name: liberty-logging-config
            items:
              - key: keystore.xml
                path: defaults/keystore.xml
              - key: logging.xml
                path: defaults/logging.xml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: erwwlite
  labels:
    name: erwwlite
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/affinity: "cookie"
    ingress.kubernetes.io/session-cookie-name: "route"
    ingress.kubernetes.io/session-cookie-hash: "sha1"
    ingress.kubernetes.io/secure-backends: "true"
    ingress.kubernetes.io/proxy-connect-timeout: "300s"
    ingress.kubernetes.io/proxy-read-timeout: "300s"
    ingress.kubernetes.io/proxy-send-timeout: "300s"
    ingress.kubernetes.io/proxy-body-size: "10m"
    ingress.kubernetes.io/upstream-keepalive-connections: "50"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        backend:
          serviceName: erwwlite
          servicePort: 9443
      - path: /WebCentralLite
        backend:
          serviceName: erwwlite
          servicePort: 9443
      - path: /WebNewOrderLite_WS_Client
        backend:
          serviceName: erwwlite
          servicePort: 9443
      - path: /WebOrderStatusLite_WS_Client
        backend:
          serviceName: erwwlite
          servicePort: 9443
      - path: /WebMonitorTransactionsLite_WebSocket1.0
        backend:
          serviceName: erwwlite
          servicePort: 9443
      - path: /WebMonitorTransactionsLite_WebSocket1.1
        backend:
          serviceName: erwwlite
          servicePort: 9443