package stateful;

public class StatefulOutput  implements java.io.Serializable {
    
    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 8971978319016054018L;
	private int total;
    private String clientIdentifier;

    public StatefulOutput() {
    }

	/**
	 * @return
	 */
	public String getClientIdentifier() {
		return clientIdentifier;
	}

	/**
	 * @param string
	 */
	public void setClientIdentifier(String string) {
		clientIdentifier = string;
	}

	/**
	 * @return
	 */
	public int getTotal() {
		return total;
	}

	/**
	 * @param i
	 */
	public void setTotal(int i) {
		total = i;
	}

 }
