package stock.query;
/*
 * Created on Oct 22, 2004
 *
 */
import jakarta.inject.Inject;
import jakarta.servlet.*;

import irwwbase.*;

/**
 * @author DACOHEN
 * 
 */

public final class SLRequestAttributeListener extends IRWWBase implements
		ServletRequestAttributeListener {
	
	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 6766352544385186003L;
	@Inject @POJOQualifier irwwbase.IRWWBase ib;

	public void attributeAdded(ServletRequestAttributeEvent event) {
		debugOut("ServletContext attribute " + event.getName() + " added");
		ib.displayOut("Stock Level listener event triggered - (using injected ref)");
		//debugOut("ServletContext attribute added");
		/*
		 * Enumeration enum = event.getServletContext().getAttributeNames();
		 * while (enum.hasMoreElements()) { String attrname =
		 * (String)enum.nextElement(); debugOut(attrname + "=" +
		 * event.getValue(attrname));
		 */
		if (event.getName().toString().indexOf("TestAttr") == -1) {
			debugOut("*** hit an attribute, but not part of the test: ****");
			debugOut("ServletContext attribute " + event.getName() + "  value "
					+ event.getValue());
			debugOut(" ");

		} else {
			debugOut("ServletContext attribute " + event.getName() + " matched");
			if (event.getValue().toString().indexOf("TestValue") == -1) {
				debugOut("**** value did not match, on add attribute in event object ****");
				//throw new UserException("*** Value did not match in attr
				// listener: "+event.getName()+event.getValue());
				ServletRequest req = event.getServletRequest();
				req.setAttribute("Status", "failed");
			} else {
				debugOut("*** value matched, on add attribute in event object **** ");
				debugOut("ServletContext attribute value: " + event.getValue());
				debugOut(" ");
			}
		}
	}

	public void attributeReplaced(ServletRequestAttributeEvent event) {
		debugOut("ServletContext attribute " + event.getName()
				+ " was changed to value " + event.getValue());
		if (event.getName().toString().indexOf("TestAttr") == -1) {
			debugOut("*** hit an attribute, but not part of the test: ****");
			debugOut("ServletContext attribute " + event.getName() + "  value "
					+ event.getValue());
			debugOut(" ");

		} else {
			debugOut("ServletContext attribute " + event.getName() + " matched");
			if (event.getValue().toString().indexOf("TestValue") == -1) {
				debugOut("**** value did not match, on attribute in event object during update ****");
				ServletRequest req = event.getServletRequest();
				req.setAttribute("Status", "failed");
			} else {
				debugOut("*** value matched, on attribute in event object during update **** ");
				debugOut("ServletContext attribute value: " + event.getValue());
				debugOut(" ");
			}
		}
	}

	public void attributeRemoved(ServletRequestAttributeEvent event) {
		debugOut("ServletContext attribute " + event.getName() + " was removed");
		if (event.getName().toString().indexOf("TestAttr") == -1) {
		} else {
			ServletRequest req = event.getServletRequest();
			req.setAttribute("RemoveStatus", "success");			
			debugOut("ServletContext attribute " + event.getName()
					+ " was removed");
		}
	}
}