package historyjpa;

import java.io.Serializable;

import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.Column;
import jakarta.persistence.Id;
import org.apache.openjpa.persistence.Persistent;
import org.apache.openjpa.persistence.jdbc.Strategy;

@Entity
@Table(name="HISTORYXML")
public class HistoryXMLJPA implements Serializable { 

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -647135556840383036L;

	//private static final long serialVersionUID= 2716055680746597905L;
	@Id
	@Column(name="H_DATA")
	private java.lang.String historyData;
	
	@Column(name="H_C_ID")
	private short historyCId;
	
	@Column(name="H_C_D_ID")
	private short historyCDId;
	
	@Column(name="H_C_W_ID")
	private short historyCWId;
	
	@Column(name="H_D_ID")
	private short historyDId;
	
	@Column(name="H_W_ID")
	private short historyWId;
	
	@Persistent 
	@Strategy("org.apache.openjpa.jdbc.meta.strats.XMLValueHandler")
	@Column(name="H_XML")
	HistoryInfo historyInfo;
	
	
	public String getHistoryData() {
		return historyData;
	}
	public void setHistoryData(String historyData) {
		this.historyData = historyData;
	}
	public short getHistoryCDId() {
		return historyCDId;
	}
	public void setHistoryCDId(short historyCDId) {
		this.historyCDId = historyCDId;
	}
	
	public short getHistoryCId() {
		return historyCId;
	}
	public void setHistoryCId(short historyCId) {
		this.historyCId = historyCId;
	}
	
	public short getHistoryCWId() {
		return historyCWId;
	}
	public void setHistoryCWId(short historyCWId) {
		this.historyCWId = historyCWId;
	}
	
	public HistoryInfo getHistoryInfo() {
		return historyInfo;
	}
	public void setHistoryInfo(HistoryInfo historyInfo) {
		this.historyInfo = historyInfo;
	}
	
//	public java.sql.Timestamp getHistoryDate() {
//	  return historyDate;
//	}
//	public void setHistoryDate(java.sql.Timestamp historyDate) {
//		this.historyDate = historyDate;
//	}
	
	public short getHistoryDId() {
		return historyDId;
	}
	public void setHistoryDId(short historyDId) {
		this.historyDId = historyDId;
	}
	
	public short getHistoryWId() {
		return historyWId;
	}
	public void setHistoryWId(short historyWId) {
		this.historyWId = historyWId;
	}


}
