//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-06/12/2007 09:21 PM(Raja)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.10.03 at 11:30:22 AM PDT 
//


package historyjpa;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HistoryData_QNAME = new QName("", "HistoryData");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HistoryDateType }
     * 
     */
    public HistoryDateType createHistoryDateType() {
        return new HistoryDateType();
    }

    /**
     * Create an instance of {@link HistoryInfo }
     * 
     */
    public HistoryInfo createHistoryInfo() {
        return new HistoryInfo();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HistoryInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HistoryData")
    public JAXBElement<HistoryInfo> createHistoryData(HistoryInfo value) {
        return new JAXBElement<HistoryInfo>(_HistoryData_QNAME, HistoryInfo.class, null, value);
    }

}
