
package deliverysession;

/**
 * @author shupert
 *
 * This SingleDeliveryOutput class encapsulates the output object from a
 * typical delivery into a single object so that we can have consistent output
 * from sychnronous and asynchronous delivery methods.  
 * 
 * Note: This class must be serializable because it is used as parameter on
 *       remote EJB method calls.
 * 
 */
public class SingleDeliveryOutput implements java.io.Serializable{

    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -3644082692651826945L;
	private boolean ivDeliverySkipped;
    private SingleDelivery ivSingleDelivery;
	
	/**
	 * @return Returns the delivery skipped flag.
	 */
	public boolean getDeliverySkipped() {
		return ivDeliverySkipped;
	}
	
	/**
	 * @param the delivery skipped flag.
	 */
	public void setDeliverySkipped(boolean deliverySkipped) {
		ivDeliverySkipped = deliverySkipped;
	}
	
	/**
	 * @return Returns the single delivery.
	 */
	public SingleDelivery getSingleDelivery() {
		return ivSingleDelivery;
	}
	
	/**
	 * @param the single delivery to set.
	 */
	public void setSingleDelivery(SingleDelivery singleDelivery) {
		ivSingleDelivery = singleDelivery;
	}

}
