/*
 * Created on Nov 30, 2004
 *
 */
package deliverysession;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * @author dacohen
 *
 */
public class SingleDelivery implements Serializable {
	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -8798878021979875208L;
	private int orderId;
	private short warehouseId;
	private short districtId;
	private short customerId;
	private BigDecimal amount;

	/**
	 * @return Returns the amount.
	 */
	public BigDecimal getAmount() {
		return amount;
	}
	/**
	 * @param amount The amount to set.
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}
	/**
	 * @return Returns the customerId.
	 */
	public short getCustomerId() {
		return customerId;
	}
	/**
	 * @param customerId The customerId to set.
	 */
	public void setCustomerId(short customerId) {
		this.customerId = customerId;
	}
	/**
	 * @return Returns the districtId.
	 */
	public short getDistrictId() {
		return districtId;
	}
	/**
	 * @param districtId The districtId to set.
	 */
	public void setDistrictId(short districtId) {
		this.districtId = districtId;
	}
	/**
	 * @return Returns the warehouseId.
	 */
	public short getWarehouseId() {
		return warehouseId;
	}
	/**
	 * @param warehouseId The warehouseId to set.
	 */
	public void setWarehouseId(short warehouseId) {
		this.warehouseId = warehouseId;
	}
	/**
	 * @return Returns the orderId.
	 */
	public int getOrderId() {
		return orderId;
	}
	/**
	 * @param orderId The orderId to set.
	 */
	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}
}
