/**
 * PriceChangeInput.java
 *
 * This file was auto-generated from WSDL
 * by the IBM WebServices WSDL2Java emitter.
 * 3
 */

package pricechangesession;

public class PriceChangeInput  implements java.io.Serializable {
    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -1288540445889115181L;
	private java.lang.String mailAttachment;
    private java.lang.String PRR;
    private double itemPrice;
    private java.lang.String[] mailtoList;
    private int itemId;
    private boolean useCmp;
    private short entityType;
    private boolean distributed;

    public PriceChangeInput() {
    }

    public java.lang.String getMailAttachment() {
        return mailAttachment;
    }

    public void setMailAttachment(java.lang.String mailAttachment) {
        this.mailAttachment = mailAttachment;
    }

    public java.lang.String getPRR() {
        return PRR;
    }

    public void setPRR(java.lang.String PRR) {
        this.PRR = PRR;
    }

    public double getItemPrice() {
        return itemPrice;
    }

    public void setItemPrice(double itemPrice) {
        this.itemPrice = itemPrice;
    }

    public java.lang.String[] getMailtoList() {
        return mailtoList;
    }

    public void setMailtoList(java.lang.String[] mailtoList) {
        this.mailtoList = mailtoList;
    }

    public int getItemId() {
        return itemId;
    }

    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    public boolean isUseCmp() {
        return useCmp;
    }

    public void setUseCmp(boolean useCmp) {
        this.useCmp = useCmp;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof PriceChangeInput)) return false;
        PriceChangeInput other = (PriceChangeInput) obj;
        /* Comment out dead code
        if (obj == null) return false;
        */
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((mailAttachment==null && other.getMailAttachment()==null) || 
             (mailAttachment!=null &&
              mailAttachment.equals(other.getMailAttachment()))) &&
            ((PRR==null && other.getPRR()==null) || 
             (PRR!=null &&
              PRR.equals(other.getPRR()))) &&
            itemPrice == other.getItemPrice() &&
            ((mailtoList==null && other.getMailtoList()==null) || 
             (mailtoList!=null &&
              java.util.Arrays.equals(mailtoList, other.getMailtoList()))) &&
            itemId == other.getItemId() &&
            useCmp == other.isUseCmp();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getMailAttachment() != null) {
            _hashCode += getMailAttachment().hashCode();
        }
        if (getPRR() != null) {
            _hashCode += getPRR().hashCode();
        }
        _hashCode += Double.valueOf(getItemPrice()).hashCode();
        if (getMailtoList() != null) {
            for (int i=0;
                 i<java.lang.reflect.Array.getLength(getMailtoList());
                 i++) {
                java.lang.Object obj = java.lang.reflect.Array.get(getMailtoList(), i);
                if (obj != null &&
                    !obj.getClass().isArray()) {
                    _hashCode += obj.hashCode();
                }
            }
        }
        _hashCode += getItemId();
        _hashCode += Boolean.valueOf(isUseCmp()).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

	/**
	 * Returns the entityType.
	 * @return short
	 */
	public short getEntityType() {
		return entityType;
	}

	/**
	 * Sets the entityType.
	 * @param entityType The entityType to set
	 */
	public void setEntityType(short entityType) {
		this.entityType = entityType;
	}

	/**
	 * @return
	 */
	public boolean isDistributed() {
		return distributed;
	}

	/**
	 * @param b
	 */
	public void setDistributed(boolean b) {
		distributed = b;
	}

}
