/**
 * PriceQuoteSingleItemOutInfo.java
 *
 * This file was auto-generated from WSDL
 * by the IBM WebServices WSDL2Java emitter.
 * 3
 */

package pricequote.lite;

public class PriceQuoteSingleItemOutInfo  implements java.io.Serializable {
    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 5484870958323562477L;
	private double outItemTotalPrice;
    private double outItemPrice;
    private int outItemId;
    private int outItemQuantity;
    private java.lang.String outItemName;

    public PriceQuoteSingleItemOutInfo() {
    }

    public double getOutItemTotalPrice() {
        return outItemTotalPrice;
    }

    public void setOutItemTotalPrice(double outItemTotalPrice) {
        this.outItemTotalPrice = outItemTotalPrice;
    }

    public double getOutItemPrice() {
        return outItemPrice;
    }

    public void setOutItemPrice(double outItemPrice) {
        this.outItemPrice = outItemPrice;
    }

    public int getOutItemId() {
        return outItemId;
    }

    public void setOutItemId(int outItemId) {
        this.outItemId = outItemId;
    }

    public int getOutItemQuantity() {
        return outItemQuantity;
    }

    public void setOutItemQuantity(int outItemQuantity) {
        this.outItemQuantity = outItemQuantity;
    }

    public java.lang.String getOutItemName() {
        return outItemName;
    }

    public void setOutItemName(java.lang.String outItemName) {
        this.outItemName = outItemName;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof PriceQuoteSingleItemOutInfo)) return false;
        PriceQuoteSingleItemOutInfo other = (PriceQuoteSingleItemOutInfo) obj;
        /* Comment out dead code
        if (obj == null) return false;
        */
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            outItemTotalPrice == other.getOutItemTotalPrice() &&
            outItemPrice == other.getOutItemPrice() &&
            outItemId == other.getOutItemId() &&
            outItemQuantity == other.getOutItemQuantity() &&
            ((outItemName==null && other.getOutItemName()==null) || 
             (outItemName!=null &&
              outItemName.equals(other.getOutItemName())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        _hashCode += Double.valueOf(getOutItemTotalPrice()).hashCode();
        _hashCode += Double.valueOf(getOutItemPrice()).hashCode();
        _hashCode += getOutItemId();
        _hashCode += getOutItemQuantity();
        if (getOutItemName() != null) {
            _hashCode += getOutItemName().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

}

