/**
 * PriceQuoteSingleItemInInfo.java
 *
 * This file was auto-generated from WSDL
 * by the IBM WebServices WSDL2Java emitter.
 * 3
 */

package pricequote.lite;

public class PriceQuoteSingleItemInInfo  implements java.io.Serializable {
    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -8431517201986787158L;
	private int inItemId;
    private java.lang.Object EJBMetaData;
    private int inItemQuantity;
	private int sleep;

    public PriceQuoteSingleItemInInfo() {
    }

    public int getInItemId() {
        return inItemId;
    }

    public void setInItemId(int inItemId) {
        this.inItemId = inItemId;
    }

    public java.lang.Object getEJBMetaData() {
        return EJBMetaData;
    }

    public void setEJBMetaData(java.lang.Object EJBMetaData) {
        this.EJBMetaData = EJBMetaData;
    }

    public int getInItemQuantity() {
        return inItemQuantity;
    }

    public void setInItemQuantity(int inItemQuantity) {
        this.inItemQuantity = inItemQuantity;
    }
    
	public int getSleep() {
		return sleep;
	}
	
	public void setSleep(int newSleep) {
		sleep = newSleep;
	}
	
    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof PriceQuoteSingleItemInInfo)) return false;
        PriceQuoteSingleItemInInfo other = (PriceQuoteSingleItemInInfo) obj;
        /*  Comment out dead code
        if (obj == null) return false;
        */
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            inItemId == other.getInItemId() &&
            ((EJBMetaData==null && other.getEJBMetaData()==null) || 
             (EJBMetaData!=null &&
              EJBMetaData.equals(other.getEJBMetaData()))) &&
            inItemQuantity == other.getInItemQuantity();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        _hashCode += getInItemId();
        if (getEJBMetaData() != null) {
            _hashCode += getEJBMetaData().hashCode();
        }
        _hashCode += getInItemQuantity();
        __hashCodeCalc = false;
        return _hashCode;
    }

}
