/**
 * PriceQuoteOutputInfo.java
 *
 * This file was auto-generated from WSDL
 * by the IBM WebServices WSDL2Java emitter.
 * 3
 */

package pricequote.lite;

public class PriceQuoteOutputInfo  implements java.io.Serializable {
    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 4444034713447609919L;
	private PriceQuoteSingleItemOutInfo[] outItemList;
    private double outTotalPrice;

    public PriceQuoteOutputInfo() {
    }

    public PriceQuoteSingleItemOutInfo[] getOutItemList() {
        return outItemList;
    }

    public void setOutItemList(PriceQuoteSingleItemOutInfo[] outItemList) {
        this.outItemList = outItemList;
    }

    public double getOutTotalPrice() {
        return outTotalPrice;
    }

    public void setOutTotalPrice(double outTotalPrice) {
        this.outTotalPrice = outTotalPrice;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof PriceQuoteOutputInfo)) return false;
        PriceQuoteOutputInfo other = (PriceQuoteOutputInfo) obj;
        /* Comment out dead code
        if (obj == null) return false;
        */
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((outItemList==null && other.getOutItemList()==null) || 
             (outItemList!=null &&
              java.util.Arrays.equals(outItemList, other.getOutItemList()))) &&
            outTotalPrice == other.getOutTotalPrice();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getOutItemList() != null) {
            for (int i=0;
                 i<java.lang.reflect.Array.getLength(getOutItemList());
                 i++) {
                java.lang.Object obj = java.lang.reflect.Array.get(getOutItemList(), i);
                if (obj != null &&
                    !obj.getClass().isArray()) {
                    _hashCode += obj.hashCode();
                }
            }
        }
        _hashCode += Double.valueOf(getOutTotalPrice()).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

}

