/**
 * PriceQuoteOutput.java
 *
 * This file was auto-generated from WSDL
 * by the IBM WebServices WSDL2Java emitter.
 * 3
 */

package pricequote.lite;

public class PriceQuoteOutput  implements java.io.Serializable {
    /**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 2072643337888773518L;
	private java.lang.String stcnum;
    private PriceQuoteOutputInfo value;
    private String status=null;
    private String stack=null;

    public PriceQuoteOutput() {
    }
/**
 * PriceQuoteOutput constructor comment.
 */
public PriceQuoteOutput(PriceQuoteOutputInfo initialValue)
{
    value = initialValue;
}
/**
 * Insert the method's description here.
 * Creation date: (4/29/2002 4:55:59 PM)
 * @return java.lang.String
 */
    public java.lang.String getStcnum() {
        return stcnum;
    }

    public void setStcnum(java.lang.String stcnum) {
        this.stcnum = stcnum;
    }

    public PriceQuoteOutputInfo getValue() {
        return value;
    }

    public void setValue(PriceQuoteOutputInfo value) {
        this.value = value;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof PriceQuoteOutput)) return false;
        PriceQuoteOutput other = (PriceQuoteOutput) obj;
        /* Comment out dead code
        if (obj == null) return false;
        */
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((stcnum==null && other.getStcnum()==null) || 
             (stcnum!=null &&
              stcnum.equals(other.getStcnum()))) &&
            ((value==null && other.getValue()==null) || 
             (value!=null &&
              value.equals(other.getValue())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getStcnum() != null) {
            _hashCode += getStcnum().hashCode();
        }
        if (getValue() != null) {
            _hashCode += getValue().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String getStack() {
		return stack;
	}
	public void setStack(String stack) {
		this.stack = stack;
	}

}

