kind: ServiceAccount
apiVersion: v1
metadata:
  name: mysvcacct
  annotations:
    argocd.argoproj.io/sync-wave: "0"
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'system:openshift:scc:privileged'
subjects:
  - kind: ServiceAccount
    name: default
  - kind: ServiceAccount
    name: mysvcacct
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
