package order.archive.lite.jdbc.el;

/**
 * Class for OrderArchiveSerlet.java's manual user input
 */
public class OrderArchiveInput implements  java.io.Serializable
{
	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = 1123088083923895210L;
	private short minWarehouseId;
	private short maxWarehouseId;
	private short minDistrictId;
	private short maxDistrictId;
	private int numOrders;

	// Constructor
	public OrderArchiveInput() {
		super();
	}

	// Getters 
	public short getMinWarehouseId() {
		return minWarehouseId;
	}
	
	public short getMaxWarehouseId() {
		return maxWarehouseId;
	}

	public short getMinDistrictId() {
		return minDistrictId;
	}
	
	public short getMaxDistrictId() {
		return maxDistrictId;
	}

	public int getNumOrders() {
		return numOrders;
	}
	
	
	// Setters
	public void setMinWarehouseId(short newWarehouseId) {
		minWarehouseId = newWarehouseId;
	}
	
	public void setMaxWarehouseId(short newWarehouseId) {
		maxWarehouseId = newWarehouseId;
	}

	public void setMinDistrictId(short newDistrictId) {
		minDistrictId = newDistrictId;
	}
	
	public void setMaxDistrictId(short newDistrictId) {
		maxDistrictId = newDistrictId;
	}

	public void setNumOrders(short newNumOrders) {
		numOrders = newNumOrders;
	}



}