package neworder.lite;

import irwwbase.ExtendedRandom;
import irwwbase.IRWWBase;
import irwwbase.MaxValues;
import irwwbase.UserException;

import java.io.Serializable;
import java.math.BigDecimal;
import java.math.RoundingMode;
//Comment out unused import
//import java.util.Date;
import java.util.Locale;
//Comment out unused import
//import javax.naming.InitialContext;

import newordersession.NewOrderInputInfo;
import newordersession.NewOrderOutputInfo;
import newordersession.NewOrderSingleItemInInfo;
import newordersession.NewOrderSingleItemOutInfo;






public class Client extends IRWWBase implements Serializable {

	//Commenting out unused variable
	//private InitialContext initialContext = null;

	/**
	 * Autogenerated UID
	 */
	private static final long serialVersionUID = -5813593347962865720L;

	private static java.lang.String _className;

	/*Commenting out unused variables
	//private String portNumber = null;

	private String hostName = null;

	private static final String DEFAULT_PROTOCOL = "IIOP";

	private static final String DEFAULT_HOST = "localhost";
	*/
 
	int numberOfItems = 0;

	public static int waitTime;

	private short inWarehouseId;

	private short inDistrictId;

	private short inCustomerId;

	private short inputType;

	private short entityType;

	private int itemId1 = 0;

	private int itemId2 = 0;

	private int itemId3 = 0;

	private int itemId4 = 0;

	private int itemId5 = 0;

	private int itemId6 = 0;

	private int itemId7 = 0;

	private int itemId8 = 0;

	private int itemId9 = 0;

	private int itemId10 = 0;

	private int itemId11 = 0;

	private int itemId12 = 0;

	private int itemId13 = 0;

	private int itemId14 = 0;

	private int itemId15 = 0;

	private int quantity1 = 0;

	private int quantity2 = 0;

	private int quantity3 = 0;

	private int quantity4 = 0;

	private int quantity5 = 0;

	private int quantity6 = 0;

	private int quantity7 = 0;

	private int quantity8 = 0;

	private int quantity9 = 0;

	private int quantity10 = 0;

	private int quantity11 = 0;

	private int quantity12 = 0;

	private int quantity13 = 0;

	private int quantity14 = 0;

	private int quantity15 = 0;

	private short itemSupplyWarehouseId1 = 0;

	private short itemSupplyWarehouseId2 = 0;

	private short itemSupplyWarehouseId3 = 0;

	private short itemSupplyWarehouseId4 = 0;

	private short itemSupplyWarehouseId5 = 0;

	private short itemSupplyWarehouseId6 = 0;

	private short itemSupplyWarehouseId7 = 0;

	private short itemSupplyWarehouseId8 = 0;

	private short itemSupplyWarehouseId9 = 0;

	private short itemSupplyWarehouseId10 = 0;

	private short itemSupplyWarehouseId11 = 0;

	private short itemSupplyWarehouseId12 = 0;

	private short itemSupplyWarehouseId13 = 0;

	private short itemSupplyWarehouseId14 = 0;

	private short itemSupplyWarehouseId15 = 0;

	NewOrderSingleItemInInfo itemElement;

	private final static byte itemListLength = 15;

	public int actualLength = 0;

	String inOrderEntryDate;

	int entityBeanType;

	String hasleep;

	boolean useCmp;

	private boolean distributed = true;
	
	NewOrderInputInfo input = null;
	
	NewOrderOutputInfo output = null;
	

	private java.lang.String[] oput;

	// I18nService declarations

	

	

	protected Locale locale;
	
	private String status="FAILED";
	
	private String stack="none";

	/**
	 * NewOrderSessionClient constructor comment.
	 */
	public Client() {
		super();
	}

	/**
	 * Insert the method's description here. Creation date: (10/11/00 11:05:09
	 * AM)
	 * 
	 * @return java.lang.String
	 */
	public String className() {
		if (_className == null)
			_className = (Client.class).getName();

		return _className;
	}

	//
	// Method to create the input structure for NewOrderTransaction
	//

	private NewOrderInputInfo generateNewOrderInput(byte db) {

		ExtendedRandom rand = new ExtendedRandom();

		NewOrderInputInfo input = new NewOrderInputInfo();

		input.setInWareHouseId((short) rand.nextInt(1, MaxValues
				.warehouseId(db)));
		
		input.setInDistrictId((short) rand.nextInt(1, MaxValues
						.districtId(db)));

		input.setInCustomerId((short) rand.nextInt(1, MaxValues
						.customerId(db)));

		numberOfItems = rand.nextInt(MaxValues.minOrderlinesPerOrder(db),
				MaxValues.orderlinesPerOrder(db));

		input.setNumberOfItems(numberOfItems);

		NewOrderSingleItemInInfo item[] = new NewOrderSingleItemInInfo[numberOfItems];

		for (int i = 0; i < numberOfItems; i++) {

			item[i] = new NewOrderSingleItemInInfo();
			item[i].setInItemId(rand.nextInt(1, MaxValues.itemId(db)));
			// item[ i ].setInItemId(item[i].getInItemId()+1); do not increment
			// any longer
			if (rand.nextBoolProb(1, 100) && MaxValues.warehouseId(db) != 1) { // remote
				// warehouse
				// 1%
				// of
				// time
				do {
					item[i].setInItemSupplyWarehouseId((short) rand.nextInt(1,
							MaxValues.warehouseId(db)));
					// item[ i
					// ].setInItemSupplyWarehouseId((short)(item[1].getInItemSupplyWarehouseId()+1));
				} while (item[i].getInItemSupplyWarehouseId() == input
						.getInWareHouseId());
			} else { // supplying warehouse = home warehouse
				item[i].setInItemSupplyWarehouseId(input.getInWareHouseId());
			}
			item[i].setInItemQuantity(rand.nextInt(1, 10));
			// item[ i
			// ].setInItemQuantity((int)(item[i].getInItemQuantity()+1));
		} // for i
		input.setInItemList(item);

		//Commenting out unused variable
		//String dateString = new String(new Date().toString());
		// actual format is : Thu Dec 09 05:50:07 EST 1999
		// required format is: 1999-12-09-11.03.22.000000

		// String year = String.valueOf((new java.util.Date().getYear())+1900);
		// String month = String.valueOf((new java.util.Date().getMonth())+1);

		input.setInOrderEntryDate(java.util.Calendar.getInstance());

		// input.inClientIdentifier = " ";
		// NewOrder is not prepared for mulitclient debugging
		int x = numberOfItems * 8 + 23;
		this.oput = new String[x];
		debugOut("<<<<length: " + this.oput.length);

		return input;
	}

	//
	// Method to initialize the output structure of NewOrderTransaction
	//

	NewOrderOutputInfo generateNewOrderOutput(byte db) {

		NewOrderOutputInfo output = new NewOrderOutputInfo();
		output.setOutWarehouseId((short) 0);
		output.setOutDistrictId((short) 0);
		output.setOutCustomerId((short) 0);
		output.setOutOrderId((short) 0);
		// double outOrderItemCount
		output.setOutCustomerLastName(" ");
		output.setOutCustomerCredit(" ");
		// double outCustomerDiscount
		// double outWarehouseTax
		// double outDistrictTax
		// output.setOutOrderEntryDate(java.util.Calendar.getInstance());
		// double outTotal
		output.setOutMsg(" ");

		debugOut("In generateNewOrderOutput, numberOfItems = " + numberOfItems);

		NewOrderSingleItemOutInfo item[] = new NewOrderSingleItemOutInfo[numberOfItems];

		for (int i = 0; i < numberOfItems; i++) {

			item[i] = new NewOrderSingleItemOutInfo();
			item[i].setOutItemId((short) 0);
			item[i].setOutItemSupplyWarehouseId((short) 0);
			item[i].setOutItemName(" ");
			// double outItemQuantity
			// double outStockQuantity
			// char outBrandGeneric
			// double outItemPrice
			// double outItemTotal
		}

		output.setOutItemList(item);

		return output;
	}

	public String[] genOutput(NewOrderOutputInfo noOutput, String[] oput) {
		// i18nService - Get Resource Bundles

	
		

		oput[0] = "****************************************************************************";
		oput[1] = "*                 NewOrder Lite   ";
		oput[2] = "*                                                                          *";
		oput[3] = "*  WarehouseID=" + noOutput.getOutWarehouseId();
		oput[4] = "*  DistrictID=" + noOutput.getOutDistrictId();
		oput[5] = "*  " + "Date=" + java.util.Calendar.getInstance().getTime();
		oput[6] = "*  " + "CustomerID=" + noOutput.getOutCustomerId();
		oput[7] = "*  " + "CustomerName=" + noOutput.getOutCustomerLastName();
		oput[8] = "*  " + "CustomerCredit=" + noOutput.getOutCustomerCredit();
		oput[9] = "*  "	+ "CustomerDiscount=" + new BigDecimal(noOutput.getOutCustomerDiscount()).setScale(2,
						RoundingMode.HALF_UP) + "%";
		oput[10] = "*                                                                          *";
		oput[11] = "*  " + "OrderID=" + noOutput.getOutOrderId();
		oput[12] = "*  " + "NumItems=" + noOutput.getOutItemList().length;
		oput[13] = "*  " + "WareHouseTax=" + noOutput.getOutWarehouseTax();
		oput[14] = "*  " + "DistrictTax=" + noOutput.getOutDistrictTax();
		oput[15] = "*                                                                          *";
		oput[16] = "*  " + "OrderDetails                                                     *";
		oput[17] = "*   ---------------------------------------------------------------------------"
				+ "----------------------------";
		int i = 0;
		int j = 0;
		for (; i < noOutput.getOutItemList().length; i++) {
			j = i * 8;
			oput[j + 18] = ("*  "
					+ "SupplyWarehouseID=" + noOutput.getOutItemList()[i].getOutItemSupplyWarehouseId());
			oput[j + 19] = ("*  " + "ItemID=" + noOutput.getOutItemList()[i].getOutItemId());
			oput[j + 20] = ("*  " + "ItemName=" + noOutput.getOutItemList()[i].getOutItemName());
			oput[j + 21] = ("*  " + "ItemQty=" + noOutput.getOutItemList()[i].getOutItemQuantity());
			oput[j + 22] = ("*  " + "StockQty=" + noOutput.getOutItemList()[i].getOutStockQuantity());
			// oput[j + 23] = "* Generic Brand: " +
			// noOutput.getOutItemList()[i].getOutBrandGeneric();
			// oput[j + 23] = ("* " + "ItemPrice=" +
			// nf.format(new
			// BigDecimal(noOutput.getOutItemList()[i].getOutItemPrice())
			// .setScale(2, BigDecimal.ROUND_HALF_UP)));
			oput[j + 23] = ("*  " + "ItemPrice=" + (new BigDecimal(
					noOutput.getOutItemList()[i].getOutItemPrice()).setScale(2,
					RoundingMode.HALF_UP)));
			// oput[j + 24] = ("* " +
			// "ItemTotalPrice=" + nf.format(new
			// BigDecimal(noOutput.getOutItemList()[i].getOutItemTotal())
			// .setScale(2, BigDecimal.ROUND_HALF_UP)));
			oput[j + 24] = ("*  "
					+ "ItemTotalPrice=" + (new BigDecimal(
					noOutput.getOutItemList()[i].getOutItemTotal()).setScale(2,
					RoundingMode.HALF_UP)));
			oput[j + 25] = "*   ---------------------------------------------------------------------------"
					+ "----------------------------";
		}
		oput[j + 26] = "*                                                                          *";
		oput[j + 27] = "*    " + "GrandTotal="
				+ new BigDecimal(noOutput.getOutTotal()).setScale(2,
						RoundingMode.HALF_UP);
		oput[j + 28] = "*                                                                          *";
		oput[j + 29] = "*    " + "Status: "+ noOutput.getOutMsg();
		oput[j + 30] = "****************************************************************************";
		return oput;
	}
	
	public String[] genOutput(NewOrderOutputInfo noOutput) {
		// i18nService - Get Resource Bundles

	
		

		this.oput[0] = "****************************************************************************";
		this.oput[1] = "*                 NewOrder Lite   ";
		this.oput[2] = "*                                                                          *";
		this.oput[3] = "*  WarehouseID=" + noOutput.getOutWarehouseId();
		this.oput[4] = "*  DistrictID=" + noOutput.getOutDistrictId();
		this.oput[5] = "*  " + "Date=" + java.util.Calendar.getInstance().getTime();
		this.oput[6] = "*  " + "CustomerID=" + noOutput.getOutCustomerId();
		this.oput[7] = "*  " + "CustomerName=" + noOutput.getOutCustomerLastName();
		this.oput[8] = "*  " + "CustomerCredit=" + noOutput.getOutCustomerCredit();
		this.oput[9] = "*  "	+ "CustomerDiscount=" + new BigDecimal(noOutput.getOutCustomerDiscount()).setScale(2,
						RoundingMode.HALF_UP) + "%";
		this.oput[10] = "*                                                                          *";
		this.oput[11] = "*  " + "OrderID=" + noOutput.getOutOrderId();
		this.oput[12] = "*  " + "NumItems=" + numberOfItems;
		this.oput[13] = "*  " + "WareHouseTax=" + noOutput.getOutWarehouseTax();
		this.oput[14] = "*  " + "DistrictTax=" + noOutput.getOutDistrictTax();
		this.oput[15] = "*                                                                          *";
		this.oput[16] = "*  " + "OrderDetails                                                     *";
		this.oput[17] = "*   ---------------------------------------------------------------------------"
				+ "----------------------------";
		int i = 0;
		int j = 0;
		for (; i < numberOfItems; i++) {
			j = i * 8;
			this.oput[j + 18] = ("*  "
					+ "SupplyWarehouseID=" + noOutput.getOutItemList()[i].getOutItemSupplyWarehouseId());
			this.oput[j + 19] = ("*  " + "ItemID=" + noOutput.getOutItemList()[i].getOutItemId());
			this.oput[j + 20] = ("*  " + "ItemName=" + noOutput.getOutItemList()[i].getOutItemName());
			this.oput[j + 21] = ("*  " + "ItemQty=" + noOutput.getOutItemList()[i].getOutItemQuantity());
			this.oput[j + 22] = ("*  " + "StockQty=" + noOutput.getOutItemList()[i].getOutStockQuantity());
			// this.oput[j + 23] = "* Generic Brand: " +
			// noOutput.getOutItemList()[i].getOutBrandGeneric();
			// this.oput[j + 23] = ("* " + "ItemPrice=" +
			// nf.format(new
			// BigDecimal(noOutput.getOutItemList()[i].getOutItemPrice())
			// .setScale(2, BigDecimal.ROUND_HALF_UP)));
			this.oput[j + 23] = ("*  " + "ItemPrice=" + (new BigDecimal(
					noOutput.getOutItemList()[i].getOutItemPrice()).setScale(2,
					RoundingMode.HALF_UP)));
			// this.oput[j + 24] = ("* " +
			// "ItemTotalPrice=" + nf.format(new
			// BigDecimal(noOutput.getOutItemList()[i].getOutItemTotal())
			// .setScale(2, BigDecimal.ROUND_HALF_UP)));
			this.oput[j + 24] = ("*  "
					+ "ItemTotalPrice=" + (new BigDecimal(
					noOutput.getOutItemList()[i].getOutItemTotal()).setScale(2,
					RoundingMode.HALF_UP)));
			this.oput[j + 25] = "*   ---------------------------------------------------------------------------"
					+ "----------------------------";
		}
		this.oput[j + 26] = "*                                                                          *";
		this.oput[j + 27] = "*    " + "GrandTotal="
				+ new BigDecimal(noOutput.getOutTotal()).setScale(2,
						RoundingMode.HALF_UP);
		this.oput[j + 28] = "*                                                                          *";
		this.oput[j + 29] = "*    " + "Status: "+ noOutput.getOutMsg();
		this.oput[j + 30] = "****************************************************************************";
		return this.oput;
	}


	/**
	 * Insert the method's description here. Creation date: (08/18/2000 5:55:24
	 * PM)
	 */

	/**
	 * Insert the method's description here. Creation date: (10/3/2001 9:41:15
	 * AM)
	 * 
	 * @return java.lang.String[]
	 */
	public NewOrderOutputInfo getOutput() {
		return output;
	}

	/* Commenting out unused private method
	private void initialDisplay(NewOrderInputInfo input) {

		
		displayOut("****************************************************************************");
		displayOut("*                 IRWW  New Order   (initial display)                      *");
		displayOut("*                                                                          *");
		displayOut("*    Warehouse ID:          " + input.getInWareHouseId());
		displayOut("*    District ID:           " + input.getInDistrictId());
		displayOut("*    Date:                  " + input.getInOrderEntryDate());
		displayOut("*    Customer ID:           " + input.getInCustomerId());
		displayOut("*                                                                          *");
		displayOut("*    Number of Items:       " + numberOfItems);
		displayOut("*                                                                          *");
		displayOut("*    SupplyWh  ItemId  ItemQuantity                                        *");
		displayOut("*   ---------------------------------------------------------------------  *");
		for (int i = 0; i < numberOfItems; i++) {
			displayOut("*      "
					+ input.getInItemList()[i].getInItemSupplyWarehouseId());
			displayOut("    " + input.getInItemList()[i].getInItemId());
			displayOut("    " + input.getInItemList()[i].getInItemQuantity());
		}
		displayOut("*                                                                          *");
		displayOut("****************************************************************************");
	}
	*/

	//
	// Method to simulate the time the user needs for keying
	//

	public void keying() {
		// super.keying( waitTime );
	}

	/**
	 * Starts the application.
	 * 
	 * @param args
	 *            an array of command-line arguments
	 */
	public static void main(java.lang.String[] args) {
		// Insert code to start the application here.

	}

	/* Comment out private method that is never used
	private void secondDisplay(NewOrderOutputInfo output) {

		displayOut("****************************************************************************");
		displayOut("*                 IRWW  New Order   (second display)                       *");
		displayOut("*                                                                          *");
		displayOut("*    Warehouse ID:          " + output.getOutWarehouseId());
		displayOut("*    District ID:           " + output.getOutDistrictId());
		displayOut("*    Date:                  "
				+ output.getOutOrderEntryDate());
		displayOut("*    Customer ID:           " + output.getOutCustomerId());
		displayOut("*    Customer Name:         "
				+ output.getOutCustomerLastName());
		displayOut("*    Customer Credit:       "
				+ output.getOutCustomerCredit());
		displayOut("*    Customer Discount:     "
				+ new BigDecimal(output.getOutCustomerDiscount()).setScale(2,
						BigDecimal.ROUND_HALF_UP) + "%");
		displayOut("*                                                                          *");
		displayOut("*    Order ID:              " + output.getOutOrderId());
		displayOut("*    Number of Items:       " + numberOfItems);
		displayOut("*    Warehouse Tax:         " + output.getOutWarehouseTax());
		displayOut("*    District Tax:          " + output.getOutDistrictTax());
		displayOut("*                                                                          *");
		displayOut("*    Wh  ItemId  Item Name                 #  Stock BG  Price  Amount      *");
		displayOut("*   ---------------------------------------------------------------------  *");
		for (int i = 0; i < numberOfItems; i++) {
			displayOut("*   "
					+ output.getOutItemList()[i].getOutItemSupplyWarehouseId());
			displayOut(" " + output.getOutItemList()[i].getOutItemId());
			displayOut(" " + output.getOutItemList()[i].getOutItemName());
			displayOut("  " + output.getOutItemList()[i].getOutItemQuantity());
			displayOut("  " + output.getOutItemList()[i].getOutStockQuantity());
			displayOut("  " + output.getOutItemList()[i].getOutBrandGeneric());
			displayOut("  "
					+ new BigDecimal(output.getOutItemList()[i]
							.getOutItemPrice()).setScale(2,
							BigDecimal.ROUND_HALF_UP));
			displayOut("  "
					+ new BigDecimal(output.getOutItemList()[i]
							.getOutItemTotal()).setScale(2,
							BigDecimal.ROUND_HALF_UP));
		}
		displayOut("*                                                                          *");
		displayOut("*    TOTAL:                 "
				+ new BigDecimal(output.getOutTotal()).setScale(2,
						BigDecimal.ROUND_HALF_UP));
		displayOut("*                                                                          *");
		displayOut("*    Execution Status:      " + output.getOutMsg());
		displayOut("****************************************************************************");
	}
	*/

	
	/**
	 * Insert the method's description here. Creation date: (10/2/2001 3:45:35
	 * PM)
	 * 
	 * @throws UserException
	 */
	public void web()  {
		//Comment out unused variable
		//String s = new String();
		//displayOut("Running Web NewOrder AutoGen Path");
		/*displayOut("Starting Time is: " + new java.util.Date().toString()
				+ ", milliseconds: "
				+ String.valueOf(System.currentTimeMillis()));*/
		status="FAILED";

		byte database = (byte) 1;
		database = dbSize();

		//Comment out unused variable
		//int iRc = 0;

		

		NewOrderInputInfo input = this.generateNewOrderInput(database);
		NewOrderOutputInfo oput = this.generateNewOrderOutput(database);
	    this.setInput(input);
	    this.setOutput(oput);
		

			

		// client.initialDisplay(input);

		// client.secondDisplay(output);

		debugOut(" Exiting NewOrderServlet ");

		/*displayOut("Ending Time is: " + new java.util.Date().toString()
				+ ", milliseconds: "
				+ String.valueOf(System.currentTimeMillis()));*/
		
		if (getStatus().indexOf("FAILED:")==-1) this.genOutput(oput);

	}

	public void webWithoutGen() throws UserException {

		//Comment out unused variable
		//String s = new String();
		//displayOut("Running Web NewOrder Manual Path");
		/*displayOut("Starting Time is: " + new java.util.Date().toString()
				+ ", milliseconds: "
				+ String.valueOf(System.currentTimeMillis()));*/
		status="FAILED";

		byte database = (byte) 1;
		database = dbSize();

		//Comment out unused variable
		//int iRc = 0;

		boolean skip = false;

		NewOrderInputInfo input = null;

		input = new NewOrderInputInfo();

		NewOrderSingleItemInInfo[] itemElement = new NewOrderSingleItemInInfo[itemListLength];

		input.setUseCmp(getUseCmp());
		input.setDistributedEJBs(isDistributed());
		debugOut("%%%%% NewOrder Client - getUseCmp() = " + getUseCmp());

		if (getInWarehouseId() != 0) {
			input.setInWareHouseId(getInWarehouseId());
		}

		if (getInDistrictId() != 0) {
			input.setInDistrictId(getInDistrictId());
		}

		if (getInCustomerId() != 0) {
			input.setInCustomerId(getInCustomerId());
		}

		input.setInOrderEntryDate(java.util.Calendar.getInstance());

		if (getItemId1() != 0) {
			itemElement[0] = new NewOrderSingleItemInInfo();
			itemElement[0].setInItemId(getItemId1());
			itemElement[0].setInItemQuantity(getQuantity1());
			itemElement[0]
					.setInItemSupplyWarehouseId(getItemSupplyWarehouseId1());
			skip = false;
		} else {
			skip = true;
		}

		if (skip == false) {
			if (getItemId2() != 0) {
				itemElement[1] = new NewOrderSingleItemInInfo();
				itemElement[1].setInItemId(getItemId2());
				itemElement[1].setInItemQuantity(getQuantity2());
				itemElement[1]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId2());
			} else {
				actualLength = 1;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId3() != 0) {
				itemElement[2] = new NewOrderSingleItemInInfo();
				itemElement[2].setInItemId(getItemId3());
				itemElement[2].setInItemQuantity(getQuantity3());
				itemElement[2]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId3());
			} else {
				actualLength = 2;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId4() != 0) {
				itemElement[3] = new NewOrderSingleItemInInfo();
				itemElement[3].setInItemId(getItemId4());
				itemElement[3].setInItemQuantity(getQuantity4());
				itemElement[3]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId4());
			} else {
				actualLength = 3;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId5() != 0) {
				itemElement[4] = new NewOrderSingleItemInInfo();
				itemElement[4].setInItemId(getItemId5());
				itemElement[4].setInItemQuantity(getQuantity5());
				itemElement[4]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId5());
			} else {
				actualLength = 4;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId6() != 0) {
				itemElement[5] = new NewOrderSingleItemInInfo();
				itemElement[5].setInItemId(getItemId6());
				itemElement[5].setInItemQuantity(getQuantity6());
				itemElement[5]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId6());
			} else {
				actualLength = 5;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId7() != 0) {
				itemElement[6] = new NewOrderSingleItemInInfo();
				itemElement[6].setInItemId(getItemId7());
				itemElement[6].setInItemQuantity(getQuantity7());
				itemElement[6]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId7());
			} else {
				actualLength = 6;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId8() != 0) {
				itemElement[7] = new NewOrderSingleItemInInfo();
				itemElement[7].setInItemId(getItemId8());
				itemElement[7].setInItemQuantity(getQuantity8());
				itemElement[7]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId8());
			} else {
				actualLength = 7;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId9() != 0) {
				itemElement[8] = new NewOrderSingleItemInInfo();
				itemElement[8].setInItemId(getItemId9());
				itemElement[8].setInItemQuantity(getQuantity9());
				itemElement[8]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId9());
			} else {
				actualLength = 8;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId10() != 0) {
				itemElement[9] = new NewOrderSingleItemInInfo();
				itemElement[9].setInItemId(getItemId10());
				itemElement[9].setInItemQuantity(getQuantity10());
				itemElement[9]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId10());
			} else {
				actualLength = 9;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId11() != 0) {
				itemElement[10] = new NewOrderSingleItemInInfo();
				itemElement[10].setInItemId(getItemId11());
				itemElement[10].setInItemQuantity(getQuantity11());
				itemElement[10]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId11());
			} else {
				actualLength = 10;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId12() != 0) {
				itemElement[11] = new NewOrderSingleItemInInfo();
				itemElement[11].setInItemId(getItemId12());
				itemElement[11].setInItemQuantity(getQuantity12());
				itemElement[11]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId12());
			} else {
				actualLength = 11;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId13() != 0) {
				itemElement[12] = new NewOrderSingleItemInInfo();
				itemElement[12].setInItemId(getItemId13());
				itemElement[12].setInItemQuantity(getQuantity13());
				itemElement[12]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId13());
			} else {
				actualLength = 12;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId14() != 0) {
				itemElement[13] = new NewOrderSingleItemInInfo();
				itemElement[13].setInItemId(getItemId14());
				itemElement[13].setInItemQuantity(getQuantity14());
				itemElement[13]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId14());
			} else {
				actualLength = 13;
				skip = true;
			}
		}

		if (skip == false) {
			if (getItemId15() != 0) {
				itemElement[14] = new NewOrderSingleItemInInfo();
				itemElement[14].setInItemId(getItemId15());
				itemElement[14].setInItemQuantity(getQuantity15());
				itemElement[14]
						.setInItemSupplyWarehouseId(getItemSupplyWarehouseId15());
				actualLength = 15;
			} else {
				actualLength = 14;
			}
		}
		int x = actualLength * 8 + 23;
		this.oput = new String[x];
		input.setNumberOfItems(actualLength);
		input.setInItemList(itemElement);
		numberOfItems = actualLength;

		NewOrderOutputInfo oput = this.generateNewOrderOutput(database);

		


		/*displayOut("Ending Time is: " + new java.util.Date().toString()
				+ ", milliseconds: "
				+ String.valueOf(System.currentTimeMillis())); */
		
		
		if (getStatus().indexOf("FAILED:")==-1) this.genOutput(oput,this.oput);

	}

	

	/**
	 * Gets the inCustomerId
	 * 
	 * @return Returns a short
	 */
	public short getInCustomerId() {
		return inCustomerId;
	}

	/**
	 * Sets the inCustomerId
	 * 
	 * @param inCustomerId
	 *            The inCustomerId to set
	 */
	public void setInCustomerId(short inCustomerId) {
		this.inCustomerId = inCustomerId;
	}

	/**
	 * Gets the inDistrictId
	 * 
	 * @return Returns a short
	 */
	public short getInDistrictId() {
		return inDistrictId;
	}

	/**
	 * Sets the inDistrictId
	 * 
	 * @param inDistrictId
	 *            The inDistrictId to set
	 */
	public void setInDistrictId(short inDistrictId) {
		this.inDistrictId = inDistrictId;
	}

	/**
	 * Gets the inWarehouseId
	 * 
	 * @return Returns a short
	 */
	public short getInWarehouseId() {
		return inWarehouseId;
	}

	/**
	 * Sets the inWarehouseId
	 * 
	 * @param inWarehouseId
	 *            The inWarehouseId to set
	 */
	public void setInWarehouseId(short inWarehouseId) {
		this.inWarehouseId = inWarehouseId;
	}

	/**
	 * Gets the itemId10
	 * 
	 * @return Returns a int
	 */
	public int getItemId10() {
		return itemId10;
	}

	/**
	 * Sets the itemId10
	 * 
	 * @param itemId10
	 *            The itemId10 to set
	 */
	public void setItemId10(int itemId10) {
		this.itemId10 = itemId10;
	}

	/**
	 * Gets the itemId11
	 * 
	 * @return Returns a int
	 */
	public int getItemId11() {
		return itemId11;
	}

	/**
	 * Sets the itemId11
	 * 
	 * @param itemId11
	 *            The itemId11 to set
	 */
	public void setItemId11(int itemId11) {
		this.itemId11 = itemId11;
	}

	/**
	 * Gets the itemId12
	 * 
	 * @return Returns a int
	 */
	public int getItemId12() {
		return itemId12;
	}

	/**
	 * Sets the itemId12
	 * 
	 * @param itemId12
	 *            The itemId12 to set
	 */
	public void setItemId12(int itemId12) {
		this.itemId12 = itemId12;
	}

	/**
	 * Gets the itemId13
	 * 
	 * @return Returns a int
	 */
	public int getItemId13() {
		return itemId13;
	}

	/**
	 * Sets the itemId13
	 * 
	 * @param itemId13
	 *            The itemId13 to set
	 */
	public void setItemId13(int itemId13) {
		this.itemId13 = itemId13;
	}

	/**
	 * Gets the itemId14
	 * 
	 * @return Returns a int
	 */
	public int getItemId14() {
		return itemId14;
	}

	/**
	 * Sets the itemId14
	 * 
	 * @param itemId14
	 *            The itemId14 to set
	 */
	public void setItemId14(int itemId14) {
		this.itemId14 = itemId14;
	}

	/**
	 * Gets the itemId15
	 * 
	 * @return Returns a int
	 */
	public int getItemId15() {
		return itemId15;
	}

	/**
	 * Sets the itemId15
	 * 
	 * @param itemId15
	 *            The itemId15 to set
	 */
	public void setItemId15(int itemId15) {
		this.itemId15 = itemId15;
	}

	/**
	 * Gets the itemId1
	 * 
	 * @return Returns a int
	 */
	public int getItemId1() {
		return itemId1;
	}

	/**
	 * Sets the itemId1
	 * 
	 * @param itemId1
	 *            The itemId1 to set
	 */
	public void setItemId1(int itemId1) {
		this.itemId1 = itemId1;
	}

	/**
	 * Gets the itemId2
	 * 
	 * @return Returns a int
	 */
	public int getItemId2() {
		return itemId2;
	}

	/**
	 * Sets the itemId2
	 * 
	 * @param itemId2
	 *            The itemId2 to set
	 */
	public void setItemId2(int itemId2) {
		this.itemId2 = itemId2;
	}

	/**
	 * Gets the itemId3
	 * 
	 * @return Returns a int
	 */
	public int getItemId3() {
		return itemId3;
	}

	/**
	 * Sets the itemId3
	 * 
	 * @param itemId3
	 *            The itemId3 to set
	 */
	public void setItemId3(int itemId3) {
		this.itemId3 = itemId3;
	}

	/**
	 * Gets the itemId4
	 * 
	 * @return Returns a int
	 */
	public int getItemId4() {
		return itemId4;
	}

	/**
	 * Sets the itemId4
	 * 
	 * @param itemId4
	 *            The itemId4 to set
	 */
	public void setItemId4(int itemId4) {
		this.itemId4 = itemId4;
	}

	/**
	 * Gets the itemId5
	 * 
	 * @return Returns a int
	 */
	public int getItemId5() {
		return itemId5;
	}

	/**
	 * Sets the itemId5
	 * 
	 * @param itemId5
	 *            The itemId5 to set
	 */
	public void setItemId5(int itemId5) {
		this.itemId5 = itemId5;
	}

	/**
	 * Gets the itemId6
	 * 
	 * @return Returns a int
	 */
	public int getItemId6() {
		return itemId6;
	}

	/**
	 * Sets the itemId6
	 * 
	 * @param itemId6
	 *            The itemId6 to set
	 */
	public void setItemId6(int itemId6) {
		this.itemId6 = itemId6;
	}

	/**
	 * Gets the itemId7
	 * 
	 * @return Returns a int
	 */
	public int getItemId7() {
		return itemId7;
	}

	/**
	 * Sets the itemId7
	 * 
	 * @param itemId7
	 *            The itemId7 to set
	 */
	public void setItemId7(int itemId7) {
		this.itemId7 = itemId7;
	}

	/**
	 * Gets the itemId8
	 * 
	 * @return Returns a int
	 */
	public int getItemId8() {
		return itemId8;
	}

	/**
	 * Sets the itemId8
	 * 
	 * @param itemId8
	 *            The itemId8 to set
	 */
	public void setItemId8(int itemId8) {
		this.itemId8 = itemId8;
	}

	/**
	 * Gets the itemId9
	 * 
	 * @return Returns a int
	 */
	public int getItemId9() {
		return itemId9;
	}

	/**
	 * Sets the itemId9
	 * 
	 * @param itemId9
	 *            The itemId9 to set
	 */
	public void setItemId9(int itemId9) {
		this.itemId9 = itemId9;
	}

	/**
	 * Gets the quantity10
	 * 
	 * @return Returns a int
	 */
	public int getQuantity10() {
		return quantity10;
	}

	/**
	 * Sets the quantity10
	 * 
	 * @param quantity10
	 *            The quantity10 to set
	 */
	public void setQuantity10(int quantity10) {
		this.quantity10 = quantity10;
	}

	/**
	 * Gets the quantity11
	 * 
	 * @return Returns a int
	 */
	public int getQuantity11() {
		return quantity11;
	}

	/**
	 * Sets the quantity11
	 * 
	 * @param quantity11
	 *            The quantity11 to set
	 */
	public void setQuantity11(int quantity11) {
		this.quantity11 = quantity11;
	}

	/**
	 * Gets the quantity12
	 * 
	 * @return Returns a int
	 */
	public int getQuantity12() {
		return quantity12;
	}

	/**
	 * Sets the quantity12
	 * 
	 * @param quantity12
	 *            The quantity12 to set
	 */
	public void setQuantity12(int quantity12) {
		this.quantity12 = quantity12;
	}

	/**
	 * Gets the quantity13
	 * 
	 * @return Returns a int
	 */
	public int getQuantity13() {
		return quantity13;
	}

	/**
	 * Sets the quantity13
	 * 
	 * @param quantity13
	 *            The quantity13 to set
	 */
	public void setQuantity13(int quantity13) {
		this.quantity13 = quantity13;
	}

	/**
	 * Gets the quantity14
	 * 
	 * @return Returns a int
	 */
	public int getQuantity14() {
		return quantity14;
	}

	/**
	 * Sets the quantity14
	 * 
	 * @param quantity14
	 *            The quantity14 to set
	 */
	public void setQuantity14(int quantity14) {
		this.quantity14 = quantity14;
	}

	/**
	 * Gets the quantity15
	 * 
	 * @return Returns a int
	 */
	public int getQuantity15() {
		return quantity15;
	}

	/**
	 * Sets the quantity15
	 * 
	 * @param quantity15
	 *            The quantity15 to set
	 */
	public void setQuantity15(int quantity15) {
		this.quantity15 = quantity15;
	}

	/**
	 * Gets the quantity1
	 * 
	 * @return Returns a int
	 */
	public int getQuantity1() {
		return quantity1;
	}

	/**
	 * Sets the quantity1
	 * 
	 * @param quantity1
	 *            The quantity1 to set
	 */
	public void setQuantity1(int quantity1) {
		this.quantity1 = quantity1;
	}

	/**
	 * Gets the quantity2
	 * 
	 * @return Returns a int
	 */
	public int getQuantity2() {
		return quantity2;
	}

	/**
	 * Sets the quantity2
	 * 
	 * @param quantity2
	 *            The quantity2 to set
	 */
	public void setQuantity2(int quantity2) {
		this.quantity2 = quantity2;
	}

	/**
	 * Gets the quantity3
	 * 
	 * @return Returns a int
	 */
	public int getQuantity3() {
		return quantity3;
	}

	/**
	 * Sets the quantity3
	 * 
	 * @param quantity3
	 *            The quantity3 to set
	 */
	public void setQuantity3(int quantity3) {
		this.quantity3 = quantity3;
	}

	/**
	 * Gets the quantity4
	 * 
	 * @return Returns a int
	 */
	public int getQuantity4() {
		return quantity4;
	}

	/**
	 * Sets the quantity4
	 * 
	 * @param quantity4
	 *            The quantity4 to set
	 */
	public void setQuantity4(int quantity4) {
		this.quantity4 = quantity4;
	}

	/**
	 * Gets the quantity5
	 * 
	 * @return Returns a int
	 */
	public int getQuantity5() {
		return quantity5;
	}

	/**
	 * Sets the quantity5
	 * 
	 * @param quantity5
	 *            The quantity5 to set
	 */
	public void setQuantity5(int quantity5) {
		this.quantity5 = quantity5;
	}

	/**
	 * Gets the quantity6
	 * 
	 * @return Returns a int
	 */
	public int getQuantity6() {
		return quantity6;
	}

	/**
	 * Sets the quantity6
	 * 
	 * @param quantity6
	 *            The quantity6 to set
	 */
	public void setQuantity6(int quantity6) {
		this.quantity6 = quantity6;
	}

	/**
	 * Gets the quantity7
	 * 
	 * @return Returns a int
	 */
	public int getQuantity7() {
		return quantity7;
	}

	/**
	 * Sets the quantity7
	 * 
	 * @param quantity7
	 *            The quantity7 to set
	 */
	public void setQuantity7(int quantity7) {
		this.quantity7 = quantity7;
	}

	/**
	 * Gets the quantity8
	 * 
	 * @return Returns a int
	 */
	public int getQuantity8() {
		return quantity8;
	}

	/**
	 * Sets the quantity8
	 * 
	 * @param quantity8
	 *            The quantity8 to set
	 */
	public void setQuantity8(int quantity8) {
		this.quantity8 = quantity8;
	}

	/**
	 * Gets the quantity9
	 * 
	 * @return Returns a int
	 */
	public int getQuantity9() {
		return quantity9;
	}

	/**
	 * Sets the quantity9
	 * 
	 * @param quantity9
	 *            The quantity9 to set
	 */
	public void setQuantity9(int quantity9) {
		this.quantity9 = quantity9;
	}

	/**
	 * Gets the useCmp
	 * 
	 * @return Returns a boolean
	 */
	public boolean getUseCmp() {
		return useCmp;
	}

	/**
	 * Sets the useCmp
	 * 
	 * @param useCmp
	 *            The useCmp to set
	 */
	public void setUseCmp(boolean useCmp) {
		this.useCmp = useCmp;
	}

	/**
	 * Gets the inOrderEntryDate
	 * 
	 * @return Returns a java.sql.Timestamp
	 */
	public String getInOrderEntryDate() {
		return inOrderEntryDate;
	}

	/**
	 * Sets the inOrderEntryDate
	 * 
	 * @param inOrderEntryDate
	 *            The inOrderEntryDate to set
	 */
	public void setInOrderEntryDate(String inOrderEntryDate) {
		this.inOrderEntryDate = inOrderEntryDate;
	}

	/**
	 * Gets the itemSupplyWarehouseId10
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId10() {
		return itemSupplyWarehouseId10;
	}

	/**
	 * Sets the itemSupplyWarehouseId10
	 * 
	 * @param itemSupplyWarehouseId10
	 *            The itemSupplyWarehouseId10 to set
	 */
	public void setItemSupplyWarehouseId10(short itemSupplyWarehouseId10) {
		this.itemSupplyWarehouseId10 = itemSupplyWarehouseId10;
	}

	/**
	 * Gets the itemSupplyWarehouseId11
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId11() {
		return itemSupplyWarehouseId11;
	}

	/**
	 * Sets the itemSupplyWarehouseId11
	 * 
	 * @param itemSupplyWarehouseId11
	 *            The itemSupplyWarehouseId11 to set
	 */
	public void setItemSupplyWarehouseId11(short itemSupplyWarehouseId11) {
		this.itemSupplyWarehouseId11 = itemSupplyWarehouseId11;
	}

	/**
	 * Gets the itemSupplyWarehouseId12
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId12() {
		return itemSupplyWarehouseId12;
	}

	/**
	 * Sets the itemSupplyWarehouseId12
	 * 
	 * @param itemSupplyWarehouseId12
	 *            The itemSupplyWarehouseId12 to set
	 */
	public void setItemSupplyWarehouseId12(short itemSupplyWarehouseId12) {
		this.itemSupplyWarehouseId12 = itemSupplyWarehouseId12;
	}

	/**
	 * Gets the itemSupplyWarehouseId13
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId13() {
		return itemSupplyWarehouseId13;
	}

	/**
	 * Sets the itemSupplyWarehouseId13
	 * 
	 * @param itemSupplyWarehouseId13
	 *            The itemSupplyWarehouseId13 to set
	 */
	public void setItemSupplyWarehouseId13(short itemSupplyWarehouseId13) {
		this.itemSupplyWarehouseId13 = itemSupplyWarehouseId13;
	}

	/**
	 * Gets the itemSupplyWarehouseId14
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId14() {
		return itemSupplyWarehouseId14;
	}

	/**
	 * Sets the itemSupplyWarehouseId14
	 * 
	 * @param itemSupplyWarehouseId14
	 *            The itemSupplyWarehouseId14 to set
	 */
	public void setItemSupplyWarehouseId14(short itemSupplyWarehouseId14) {
		this.itemSupplyWarehouseId14 = itemSupplyWarehouseId14;
	}

	/**
	 * Gets the itemSupplyWarehouseId15
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId15() {
		return itemSupplyWarehouseId15;
	}

	/**
	 * Sets the itemSupplyWarehouseId15
	 * 
	 * @param itemSupplyWarehouseId15
	 *            The itemSupplyWarehouseId15 to set
	 */
	public void setItemSupplyWarehouseId15(short itemSupplyWarehouseId15) {
		this.itemSupplyWarehouseId15 = itemSupplyWarehouseId15;
	}

	/**
	 * Gets the itemSupplyWarehouseId1
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId1() {
		return itemSupplyWarehouseId1;
	}

	/**
	 * Sets the itemSupplyWarehouseId1
	 * 
	 * @param itemSupplyWarehouseId1
	 *            The itemSupplyWarehouseId1 to set
	 */
	public void setItemSupplyWarehouseId1(short itemSupplyWarehouseId1) {
		this.itemSupplyWarehouseId1 = itemSupplyWarehouseId1;
	}

	/**
	 * Gets the itemSupplyWarehouseId2
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId2() {
		return itemSupplyWarehouseId2;
	}

	/**
	 * Sets the itemSupplyWarehouseId2
	 * 
	 * @param itemSupplyWarehouseId2
	 *            The itemSupplyWarehouseId2 to set
	 */
	public void setItemSupplyWarehouseId2(short itemSupplyWarehouseId2) {
		this.itemSupplyWarehouseId2 = itemSupplyWarehouseId2;
	}

	/**
	 * Gets the itemSupplyWarehouseId3
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId3() {
		return itemSupplyWarehouseId3;
	}

	/**
	 * Sets the itemSupplyWarehouseId3
	 * 
	 * @param itemSupplyWarehouseId3
	 *            The itemSupplyWarehouseId3 to set
	 */
	public void setItemSupplyWarehouseId3(short itemSupplyWarehouseId3) {
		this.itemSupplyWarehouseId3 = itemSupplyWarehouseId3;
	}

	/**
	 * Gets the itemSupplyWarehouseId4
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId4() {
		return itemSupplyWarehouseId4;
	}

	/**
	 * Sets the itemSupplyWarehouseId4
	 * 
	 * @param itemSupplyWarehouseId4
	 *            The itemSupplyWarehouseId4 to set
	 */
	public void setItemSupplyWarehouseId4(short itemSupplyWarehouseId4) {
		this.itemSupplyWarehouseId4 = itemSupplyWarehouseId4;
	}

	/**
	 * Gets the itemSupplyWarehouseId5
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId5() {
		return itemSupplyWarehouseId5;
	}

	/**
	 * Sets the itemSupplyWarehouseId5
	 * 
	 * @param itemSupplyWarehouseId5
	 *            The itemSupplyWarehouseId5 to set
	 */
	public void setItemSupplyWarehouseId5(short itemSupplyWarehouseId5) {
		this.itemSupplyWarehouseId5 = itemSupplyWarehouseId5;
	}

	/**
	 * Gets the itemSupplyWarehouseId6
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId6() {
		return itemSupplyWarehouseId6;
	}

	/**
	 * Sets the itemSupplyWarehouseId6
	 * 
	 * @param itemSupplyWarehouseId6
	 *            The itemSupplyWarehouseId6 to set
	 */
	public void setItemSupplyWarehouseId6(short itemSupplyWarehouseId6) {
		this.itemSupplyWarehouseId6 = itemSupplyWarehouseId6;
	}

	/**
	 * Gets the itemSupplyWarehouseId7
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId7() {
		return itemSupplyWarehouseId7;
	}

	/**
	 * Sets the itemSupplyWarehouseId7
	 * 
	 * @param itemSupplyWarehouseId7
	 *            The itemSupplyWarehouseId7 to set
	 */
	public void setItemSupplyWarehouseId7(short itemSupplyWarehouseId7) {
		this.itemSupplyWarehouseId7 = itemSupplyWarehouseId7;
	}

	/**
	 * Gets the itemSupplyWarehouseId8
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId8() {
		return itemSupplyWarehouseId8;
	}

	/**
	 * Sets the itemSupplyWarehouseId8
	 * 
	 * @param itemSupplyWarehouseId8
	 *            The itemSupplyWarehouseId8 to set
	 */
	public void setItemSupplyWarehouseId8(short itemSupplyWarehouseId8) {
		this.itemSupplyWarehouseId8 = itemSupplyWarehouseId8;
	}

	/**
	 * Gets the itemSupplyWarehouseId9
	 * 
	 * @return Returns a short
	 */
	public short getItemSupplyWarehouseId9() {
		return itemSupplyWarehouseId9;
	}

	/**
	 * Sets the itemSupplyWarehouseId9
	 * 
	 * @param itemSupplyWarehouseId9
	 *            The itemSupplyWarehouseId9 to set
	 */
	public void setItemSupplyWarehouseId9(short itemSupplyWarehouseId9) {
		this.itemSupplyWarehouseId9 = itemSupplyWarehouseId9;
	}

	/**
	 * Returns the entityBeanType.
	 * 
	 * @return int
	 */
	public int getEntityBeanType() {
		return entityBeanType;
	}

	/**
	 * Sets the entityBeanType.
	 * 
	 * @param entityBeanType
	 *            The entityBeanType to set
	 */
	public void setEntityBeanType(int entityBeanType) {
		this.entityBeanType = entityBeanType;
	}

	/**
	 * Returns the entityType.
	 * 
	 * @return short
	 */
	public short getEntityType() {
		return entityType;
	}

	/**
	 * Sets the entityType.
	 * 
	 * @param entityType
	 *            The entityType to set
	 */
	public void setEntityType(short entityType) {
		this.entityType = entityType;
	}

	/**
	 * @return
	 */
	public boolean isDistributed() {
		return distributed;
	}

	/**
	 * @param b
	 */
	public void setDistributed(boolean b) {
		distributed = b;
	}

	

	public short getInputType() {
		return inputType;
	}

	public void setInputType(short inputType) {
		this.inputType = inputType;
	}

	public String getHasleep() {
		return hasleep;
	}

	public void setHasleep(String hasleep) {
		this.hasleep = hasleep;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStack() {
		return stack;
	}

	public void setStack(String stack) {
		this.stack = stack;
	}

	public NewOrderInputInfo getInput() {
		return input;
	}

	public void setInput(NewOrderInputInfo input) {
		this.input = input;
	}

	public void setOutput(NewOrderOutputInfo output) {
		this.output = output;
	}

	public java.lang.String[] getOput() {
		return oput;
	}

	public void setOput(java.lang.String[] oput) {
		this.oput = oput;
	}

}
