name: Java Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write 

jobs:
  release:
    runs-on: ubuntu-latest
    
    env:
      JAVA_HOME: ${{ github.workspace }}/graalvm-ce-java11-22.3.3

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 11 from GraalVM
        run: |
          echo "${{ env.JAVA_HOME }}/bin" >> $GITHUB_PATH
          wget https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java11-linux-amd64-22.3.3.tar.gz
          tar -xvzf graalvm-ce-java11-linux-amd64-22.3.3.tar.gz
          ${{ env.JAVA_HOME }}/bin/gu install native-image

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean fatJar

      - name: Build Changelog
        id: gen_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          failOnError: "true"
          configuration: .github/workflows/release_config.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/*.jar
          body: ${{ steps.gen_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
