ARG BASE_IMAGE=icr.io/appcafe/open-liberty:kernel-slim-java8-openj9-ubi

FROM $BASE_IMAGE


COPY ERWWLiteRuntimeUtil/src/publish/databaseDrivers/db2V9Drivers/db2jcc4.jar /opt/ibm/wlp/usr/shared/resources/db2drivers/db2jcc4.jar
COPY ERWWLiteRuntimeUtil/src/publish/databaseDrivers/db2V9Drivers/db2jcc_license_cu.jar /opt/ibm/wlp/usr/shared/resources/db2drivers/db2jcc_license_cu.jar
COPY --chown=1001:0 ERWWLiteRuntimeUtil/src/publish/servers/server.xml /config/server.xml
COPY --chown=1001:0 ERWWLiteRuntimeUtil/src/publish/files/jvm.options /config/jvm.options
COPY --chown=1001:0 ERWWLiteRuntimeUtil/src/publish/files/bootstrap.properties /config/bootstrap.properties
COPY --chown=1001:0 ERWW_Lite_WS_Client_EAR/target/ERWW_Lite_WS_Client_EAR.ear /config/apps/ERWW_Lite_WS_Client_EAR.ear
COPY --chown=1001:0 ERWW_Lite_EAR/target/ERWW_Lite_EAR.ear /config/apps/ERWW_Lite_EAR.ear

User root

RUN --mount=type=secret,id=token --mount=type=secret,id=user\
       mkdir -p /mytemp && cd /mytemp \
       && curl --retry 7 -sSf -u $(cat /run/secrets/user):$(cat /run/secrets/token) \
      -O 'https://na.artifactory.swg-devops.com/artifactory/hyc-wassvt-team-maven-virtual/svtMessageApp/svtMessageApp/2.0.2/svtMessageApp-2.0.2.war' \
      && curl --retry 7 -sSf -u $(cat /run/secrets/user):$(cat /run/secrets/token) \
      -O 'https://na.artifactory.swg-devops.com/artifactory/hyc-wassvt-team-maven-virtual/microwebapp/microwebapp/2.0.1/microwebapp-2.0.1.war' \
      && curl --retry 7 -sSf -u $(cat /run/secrets/user):$(cat /run/secrets/token) \
      -O 'https://na.artifactory.swg-devops.com/artifactory/hyc-wassvt-team-maven-virtual/com/ibm/ws/lumberjack/badapp/2.0.1/badapp-2.0.1.war' \
      && chown -R 1001:0 /mytemp/*.war  && mv /mytemp/*.war /config/dropins
      
user 1001

ARG VERBOSE=true
ARG FULL_IMAGE=false

RUN if [ "$FULL_IMAGE" = "true" ] ; then echo "Skip running features.sh for full image" ; else features.sh ; fi
RUN configure.sh
